In [ ]:
simport pandas as pd
import numpy as np
import os

print("Libraries imported successfully.")

Libraries imported successfully.

In [ ]:
import os

print("Files available in Colab:")
for file in os.listdir('/content'):
    print("-", file)

Files available in Colab:
- .config
- DimTables.xlsx
- FactInternetSales.xlsx
- FactResellerSales.xlsx
- sample_data

In [ ]:
# Read the Excel workbooks
dim_tables = pd.ExcelFile('/content/DimTables.xlsx')
internet_sales_file = pd.ExcelFile('/content/FactInternetSales.xlsx')
reseller_sales_file = pd.ExcelFile('/content/FactResellerSales.xlsx')

print("DimTables sheets:")
print(dim_tables.sheet_names)

print("\nFactInternetSales sheets:")
print(internet_sales_file.sheet_names)

print("\nFactResellerSales sheets:")
print(reseller_sales_file.sheet_names)

DimTables sheets:
['DimCustomer', 'DimEmployee', 'DimGeography', 'DimProduct', 'DimReseller', 'DimSalesTerritory']

FactInternetSales sheets:
['FactInternetSales']

FactResellerSales sheets:
['FactResellerSales']

In [ ]:
# Load dimension tables
dim_customer = pd.read_excel('/content/DimTables.xlsx', sheet_name='DimCustomer')
dim_employee = pd.read_excel('/content/DimTables.xlsx', sheet_name='DimEmployee')
dim_geography = pd.read_excel('/content/DimTables.xlsx', sheet_name='DimGeography')
dim_product = pd.read_excel('/content/DimTables.xlsx', sheet_name='DimProduct')
dim_reseller = pd.read_excel('/content/DimTables.xlsx', sheet_name='DimReseller')
dim_sales_territory = pd.read_excel('/content/DimTables.xlsx', sheet_name='DimSalesTerritory')

# Load fact tables
fact_internet_sales = pd.read_excel(
    '/content/FactInternetSales.xlsx',
    sheet_name='FactInternetSales'
)

fact_reseller_sales = pd.read_excel(
    '/content/FactResellerSales.xlsx',
    sheet_name='FactResellerSales'
)

print("All tables loaded successfully.\n")

print("Dimension Tables:")
print("DimCustomer:", dim_customer.shape)
print("DimEmployee:", dim_employee.shape)
print("DimGeography:", dim_geography.shape)
print("DimProduct:", dim_product.shape)
print("DimReseller:", dim_reseller.shape)
print("DimSalesTerritory:", dim_sales_territory.shape)

print("\nFact Tables:")
print("FactInternetSales:", fact_internet_sales.shape)
print("FactResellerSales:", fact_reseller_sales.shape)

All tables loaded successfully.

Dimension Tables:
DimCustomer: (18484, 13)
DimEmployee: (21, 9)
DimGeography: (655, 6)
DimProduct: (397, 7)
DimReseller: (701, 4)
DimSalesTerritory: (11, 4)

Fact Tables:
FactInternetSales: (60398, 13)
FactResellerSales: (60899, 14)

In [ ]:
tables = {
    "DimCustomer": dim_customer,
    "DimEmployee": dim_employee,
    "DimGeography": dim_geography,
    "DimProduct": dim_product,
    "DimReseller": dim_reseller,
    "DimSalesTerritory": dim_sales_territory,
    "FactInternetSales": fact_internet_sales,
    "FactResellerSales": fact_reseller_sales
}

for name, df in tables.items():
    print("=" * 70)
    print(name)
    print("=" * 70)
    print("Columns:")
    print(list(df.columns))
    print("\nData Types:")
    print(df.dtypes)
    print()

======================================================================
DimCustomer
======================================================================
Columns:
['CustomerKey', 'GeographyKey', 'CustomerName', 'BirthDate', 'MaritalStatus', 'Gender', 'EmailAddress', 'YearlyIncome', 'Education', 'Occupation', 'HouseOwnerFlag', 'Address', 'FirstPurchaseDate']

Data Types:
CustomerKey                   int64
GeographyKey                  int64
CustomerName                 object
BirthDate            datetime64[ns]
MaritalStatus                object
Gender                       object
EmailAddress                 object
YearlyIncome                  int64
Education                    object
Occupation                   object
HouseOwnerFlag                int64
Address                      object
FirstPurchaseDate    datetime64[ns]
dtype: object

======================================================================
DimEmployee
======================================================================
Columns:
['EmployeeKey', 'ParentEmployeeKey', 'SalesTerritoryKey', 'EmployeeName', 'Title', 'EmailAddress', 'DepartmentName', 'HireDate', 'BirthDate']

Data Types:
EmployeeKey                   int64
ParentEmployeeKey           float64
SalesTerritoryKey             int64
EmployeeName                 object
Title                        object
EmailAddress                 object
DepartmentName               object
HireDate             datetime64[ns]
BirthDate            datetime64[ns]
dtype: object

======================================================================
DimGeography
======================================================================
Columns:
['GeographyKey', 'City', 'State', 'Country', 'PostalCode', 'SalesTerritoryKey']

Data Types:
GeographyKey          int64
City                 object
State                object
Country              object
PostalCode           object
SalesTerritoryKey     int64
dtype: object

======================================================================
DimProduct
======================================================================
Columns:
['ProductKey', 'ProductSubcategoryKey', 'Product', 'Color', 'Model', 'Subcategory', 'Category']

Data Types:
ProductKey                int64
ProductSubcategoryKey     int64
Product                  object
Color                    object
Model                    object
Subcategory              object
Category                 object
dtype: object

======================================================================
DimReseller
======================================================================
Columns:
['ResellerKey', 'GeographyKey', 'BusinessType', 'ResellerName']

Data Types:
ResellerKey      int64
GeographyKey     int64
BusinessType    object
ResellerName    object
dtype: object

======================================================================
DimSalesTerritory
======================================================================
Columns:
['SalesTerritoryKey', 'SalesTerritoryRegion', 'SalesTerritoryCountry', 'SalesTerritoryGroup']

Data Types:
SalesTerritoryKey         int64
SalesTerritoryRegion     object
SalesTerritoryCountry    object
SalesTerritoryGroup      object
dtype: object

======================================================================
FactInternetSales
======================================================================
Columns:
['ProductKey', 'CustomerKey', 'SalesTerritoryKey', 'SalesOrderNumber', 'SalesOrderLineNumber', 'DiscountAmount', 'TotalProductCost', 'SalesAmount', 'Freight', 'CarrierTrackingNumber', 'OrderDate', 'DueDate', 'ShipDate']

Data Types:
ProductKey                 int64
CustomerKey                int64
SalesTerritoryKey          int64
SalesOrderNumber          object
SalesOrderLineNumber       int64
DiscountAmount             int64
TotalProductCost         float64
SalesAmount              float64
Freight                  float64
CarrierTrackingNumber    float64
OrderDate                 object
DueDate                   object
ShipDate                  object
dtype: object

======================================================================
FactResellerSales
======================================================================
Columns:
['ProductKey', 'ResellerKey', 'EmployeeKey', 'SalesTerritoryKey', 'SalesOrderNumber', 'SalesOrderLineNumber', 'DiscountAmount', 'TotalProductCost', 'SalesAmount', 'Freight', 'CarrierTrackingNumber', 'OrderDate', 'DueDate', 'ShipDate']

Data Types:
ProductKey               float64
ResellerKey              float64
EmployeeKey              float64
SalesTerritoryKey        float64
SalesOrderNumber          object
SalesOrderLineNumber     float64
DiscountAmount           float64
TotalProductCost         float64
SalesAmount              float64
Freight                  float64
CarrierTrackingNumber     object
OrderDate                 object
DueDate                   object
ShipDate                  object
dtype: object

In [ ]:
for name, df in tables.items():
    print("=" * 70)
    print(name)
    print("=" * 70)

    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if len(missing) == 0:
        print("No missing values found.")
    else:
        print(missing)

    print()

======================================================================
DimCustomer
======================================================================
No missing values found.

======================================================================
DimEmployee
======================================================================
ParentEmployeeKey    1
dtype: int64

======================================================================
DimGeography
======================================================================
No missing values found.

======================================================================
DimProduct
======================================================================
Color    56
dtype: int64

======================================================================
DimReseller
======================================================================
No missing values found.

======================================================================
DimSalesTerritory
======================================================================
SalesTerritoryRegion     1
SalesTerritoryCountry    1
SalesTerritoryGroup      1
dtype: int64

======================================================================
FactInternetSales
======================================================================
CarrierTrackingNumber    60398
dtype: int64

======================================================================
FactResellerSales
======================================================================
ProductKey               44
ResellerKey              44
EmployeeKey              44
SalesTerritoryKey        44
SalesOrderNumber         44
SalesOrderLineNumber     44
DiscountAmount           44
TotalProductCost          3
SalesAmount               3
Freight                  44
CarrierTrackingNumber    44
OrderDate                44
DueDate                  44
ShipDate                 44
dtype: int64

In [ ]:
# Display rows containing missing values in FactResellerSales
reseller_missing_rows = fact_reseller_sales[
    fact_reseller_sales.isnull().any(axis=1)
]

print("Number of rows with missing values:", len(reseller_missing_rows))

display(reseller_missing_rows)

Number of rows with missing values: 44

,ProductKey,ResellerKey,EmployeeKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,DiscountAmount,TotalProductCost,SalesAmount,Freight,CarrierTrackingNumber,OrderDate,DueDate,ShipDate
352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.722951e+05,4.893286e+05,NaN,NaN,NaN,NaN,NaN
353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.469460e+06,1.538408e+06,NaN,NaN,NaN,NaN,NaN
1733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.108483e+06,1.165897e+06,NaN,NaN,NaN,NaN,NaN
2233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.171295e+05,8.447210e+05,NaN,NaN,NaN,NaN,NaN
3340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.236063e+06,2.324136e+06,NaN,NaN,NaN,NaN,NaN
4144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.633078e+06,1.702945e+06,NaN,NaN,NaN,NaN,NaN
4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.904294e+05,7.131167e+05,NaN,NaN,NaN,NaN,NaN
5389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.830481e+06,1.900789e+06,NaN,NaN,NaN,NaN,NaN
6043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.396767e+06,1.455280e+06,NaN,NaN,NaN,NaN,NaN
6538,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.546459e+05,8.828999e+05,NaN,NaN,NaN,NaN,NaN
7651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.181837e+06,2.269117e+06,NaN,NaN,NaN,NaN,NaN
8471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.607008e+06,1.001804e+06,NaN,NaN,NaN,NaN,NaN
10195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.338001e+06,2.393690e+06,NaN,NaN,NaN,NaN,NaN
10196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.468826e+06,3.601191e+06,NaN,NaN,NaN,NaN,NaN
15347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.735886e+06,2.885359e+06,NaN,NaN,NaN,NaN,NaN
16754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.724518e+06,1.802154e+06,NaN,NaN,NaN,NaN,NaN
19100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.919120e+06,3.053816e+06,NaN,NaN,NaN,NaN,NaN
20833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.073508e+06,2.185213e+06,NaN,NaN,NaN,NaN,NaN
21817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.267385e+06,1.317542e+06,NaN,NaN,NaN,NaN,NaN
23482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.308084e+06,2.384847e+06,NaN,NaN,NaN,NaN,NaN
24698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.497550e+06,1.563955e+06,NaN,NaN,NaN,NaN,NaN
26148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.782337e+06,1.865278e+06,NaN,NaN,NaN,NaN,NaN
28455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.765546e+06,2.880753e+06,NaN,NaN,NaN,NaN,NaN
30154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.887464e+06,1.987873e+06,NaN,NaN,NaN,NaN,NaN
32341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.847508e+06,2.665651e+06,NaN,NaN,NaN,NaN,NaN
32342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.463793e+06,4.212972e+06,NaN,NaN,NaN,NaN,NaN
39858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.325499e+06,4.047574e+06,NaN,NaN,NaN,NaN,NaN
41669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.285347e+06,2.282116e+06,NaN,NaN,NaN,NaN,NaN
44574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.460755e+06,3.483161e+06,NaN,NaN,NaN,NaN,NaN
47604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.479960e+06,3.510949e+06,NaN,NaN,NaN,NaN,NaN
48987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.657962e+06,1.662547e+06,NaN,NaN,NaN,NaN,NaN
51064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.687670e+06,2.699301e+06,NaN,NaN,NaN,NaN,NaN
51066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.554948e+03,1.466010e+03,NaN,NaN,NaN,NaN,NaN
53243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.730455e+06,2.737188e+06,NaN,NaN,NaN,NaN,NaN
53248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.191829e+03,2.183376e+03,NaN,NaN,NaN,NaN,NaN
55042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.199567e+06,2.204542e+06,NaN,NaN,NaN,NaN,NaN
55045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.046738e+02,8.156400e+01,NaN,NaN,NaN,NaN,NaN
57891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.340792e+06,3.314519e+06,NaN,NaN,NaN,NaN,NaN
57894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.480582e+02,7.557840e+02,NaN,NaN,NaN,NaN,NaN
60897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.430306e+06,3.415479e+06,NaN,NaN,NaN,NaN,NaN
60898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.998011e+07,8.045060e+07,NaN,NaN,NaN,NaN,NaN

In [ ]:
for name, df in tables.items():
    print("=" * 70)
    print(name)
    print("=" * 70)
    print("Duplicate rows:", df.duplicated().sum())
    print()

======================================================================
DimCustomer
======================================================================
Duplicate rows: 0

======================================================================
DimEmployee
======================================================================
Duplicate rows: 0

======================================================================
DimGeography
======================================================================
Duplicate rows: 0

======================================================================
DimProduct
======================================================================
Duplicate rows: 0

======================================================================
DimReseller
======================================================================
Duplicate rows: 0

======================================================================
DimSalesTerritory
======================================================================
Duplicate rows: 0

======================================================================
FactInternetSales
======================================================================
Duplicate rows: 0

======================================================================
FactResellerSales
======================================================================
Duplicate rows: 2

In [ ]:
duplicates_reseller = fact_reseller_sales[
    fact_reseller_sales.duplicated(keep=False)
].sort_values(
    by=['SalesOrderNumber', 'SalesOrderLineNumber'],
    na_position='last'
)

print("Duplicate records found:", len(duplicates_reseller))

display(duplicates_reseller)

Duplicate records found: 3

,ProductKey,ResellerKey,EmployeeKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,DiscountAmount,TotalProductCost,SalesAmount,Freight,CarrierTrackingNumber,OrderDate,DueDate,ShipDate
353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
before_rows = len(fact_reseller_sales)

fact_reseller_sales = fact_reseller_sales.dropna(how='all').reset_index(drop=True)

after_rows = len(fact_reseller_sales)

print("Rows before cleaning:", before_rows)
print("Completely blank rows removed:", before_rows - after_rows)
print("Rows after cleaning:", after_rows)
print("Duplicate rows remaining:", fact_reseller_sales.duplicated().sum())

Rows before cleaning: 60899
Completely blank rows removed: 3
Rows after cleaning: 60896
Duplicate rows remaining: 0

In [ ]:
key_columns = {
    "DimCustomer": "CustomerKey",
    "DimEmployee": "EmployeeKey",
    "DimGeography": "GeographyKey",
    "DimProduct": "ProductKey",
    "DimReseller": "ResellerKey",
    "DimSalesTerritory": "SalesTerritoryKey"
}

for table_name, key_col in key_columns.items():
    df = tables[table_name]

    print("=" * 70)
    print(table_name)
    print("=" * 70)
    print("Total rows:", len(df))
    print("Unique", key_col + ":", df[key_col].nunique())
    print("Duplicate", key_col + ":", df[key_col].duplicated().sum())
    print()

======================================================================
DimCustomer
======================================================================
Total rows: 18484
Unique CustomerKey: 18484
Duplicate CustomerKey: 0

======================================================================
DimEmployee
======================================================================
Total rows: 21
Unique EmployeeKey: 21
Duplicate EmployeeKey: 0

======================================================================
DimGeography
======================================================================
Total rows: 655
Unique GeographyKey: 655
Duplicate GeographyKey: 0

======================================================================
DimProduct
======================================================================
Total rows: 397
Unique ProductKey: 397
Duplicate ProductKey: 0

======================================================================
DimReseller
======================================================================
Total rows: 701
Unique ResellerKey: 701
Duplicate ResellerKey: 0

======================================================================
DimSalesTerritory
======================================================================
Total rows: 11
Unique SalesTerritoryKey: 11
Duplicate SalesTerritoryKey: 0

In [ ]:
print("=" * 70)
print("FactInternetSales - Foreign Key Validation")
print("=" * 70)

checks = {
    "CustomerKey": dim_customer["CustomerKey"],
    "ProductKey": dim_product["ProductKey"],
    "SalesTerritoryKey": dim_sales_territory["SalesTerritoryKey"]
}

for fact_col, dim_keys in checks.items():
    invalid_count = (~fact_internet_sales[fact_col].isin(dim_keys)).sum()

    print(f"{fact_col}:")
    print(f"  Invalid foreign keys: {invalid_count}")
    print()

======================================================================
FactInternetSales - Foreign Key Validation
======================================================================
CustomerKey:
  Invalid foreign keys: 0

ProductKey:
  Invalid foreign keys: 0

SalesTerritoryKey:
  Invalid foreign keys: 0

In [ ]:
print("=" * 70)
print("FactResellerSales - Foreign Key Validation")
print("=" * 70)

checks = {
    "ProductKey": dim_product["ProductKey"],
    "ResellerKey": dim_reseller["ResellerKey"],
    "EmployeeKey": dim_employee["EmployeeKey"],
    "SalesTerritoryKey": dim_sales_territory["SalesTerritoryKey"]
}

for fact_col, dim_keys in checks.items():
    invalid_count = (~fact_reseller_sales[fact_col].isin(dim_keys)).sum()

    print(f"{fact_col}:")
    print(f"  Invalid foreign keys: {invalid_count}")
    print()

======================================================================
FactResellerSales - Foreign Key Validation
======================================================================
ProductKey:
  Invalid foreign keys: 41

ResellerKey:
  Invalid foreign keys: 41

EmployeeKey:
  Invalid foreign keys: 41

SalesTerritoryKey:
  Invalid foreign keys: 41

In [ ]:
invalid_reseller_rows = fact_reseller_sales[
    ~fact_reseller_sales["ProductKey"].isin(dim_product["ProductKey"])
    | ~fact_reseller_sales["ResellerKey"].isin(dim_reseller["ResellerKey"])
    | ~fact_reseller_sales["EmployeeKey"].isin(dim_employee["EmployeeKey"])
    | ~fact_reseller_sales["SalesTerritoryKey"].isin(dim_sales_territory["SalesTerritoryKey"])
]

print("Total rows with invalid foreign keys:", len(invalid_reseller_rows))

display(invalid_reseller_rows)

Total rows with invalid foreign keys: 41

,ProductKey,ResellerKey,EmployeeKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,DiscountAmount,TotalProductCost,SalesAmount,Freight,CarrierTrackingNumber,OrderDate,DueDate,ShipDate
352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.722951e+05,4.893286e+05,NaN,NaN,NaN,NaN,NaN
1138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.469460e+06,1.538408e+06,NaN,NaN,NaN,NaN,NaN
1732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.108483e+06,1.165897e+06,NaN,NaN,NaN,NaN,NaN
2232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.171295e+05,8.447210e+05,NaN,NaN,NaN,NaN,NaN
3339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.236063e+06,2.324136e+06,NaN,NaN,NaN,NaN,NaN
4143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.633078e+06,1.702945e+06,NaN,NaN,NaN,NaN,NaN
4521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.904294e+05,7.131167e+05,NaN,NaN,NaN,NaN,NaN
5388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.830481e+06,1.900789e+06,NaN,NaN,NaN,NaN,NaN
6042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.396767e+06,1.455280e+06,NaN,NaN,NaN,NaN,NaN
6537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.546459e+05,8.828999e+05,NaN,NaN,NaN,NaN,NaN
7650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.181837e+06,2.269117e+06,NaN,NaN,NaN,NaN,NaN
8470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.607008e+06,1.001804e+06,NaN,NaN,NaN,NaN,NaN
10194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.338001e+06,2.393690e+06,NaN,NaN,NaN,NaN,NaN
13159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.468826e+06,3.601191e+06,NaN,NaN,NaN,NaN,NaN
15345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.735886e+06,2.885359e+06,NaN,NaN,NaN,NaN,NaN
16752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.724518e+06,1.802154e+06,NaN,NaN,NaN,NaN,NaN
19098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.919120e+06,3.053816e+06,NaN,NaN,NaN,NaN,NaN
20831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.073508e+06,2.185213e+06,NaN,NaN,NaN,NaN,NaN
21815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.267385e+06,1.317542e+06,NaN,NaN,NaN,NaN,NaN
23480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.308084e+06,2.384847e+06,NaN,NaN,NaN,NaN,NaN
24696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.497550e+06,1.563955e+06,NaN,NaN,NaN,NaN,NaN
26146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.782337e+06,1.865278e+06,NaN,NaN,NaN,NaN,NaN
28453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.765546e+06,2.880753e+06,NaN,NaN,NaN,NaN,NaN
30152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.887464e+06,1.987873e+06,NaN,NaN,NaN,NaN,NaN
32339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.847508e+06,2.665651e+06,NaN,NaN,NaN,NaN,NaN
36094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.463793e+06,4.212972e+06,NaN,NaN,NaN,NaN,NaN
39855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.325499e+06,4.047574e+06,NaN,NaN,NaN,NaN,NaN
41666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.285347e+06,2.282116e+06,NaN,NaN,NaN,NaN,NaN
44571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.460755e+06,3.483161e+06,NaN,NaN,NaN,NaN,NaN
47601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.479960e+06,3.510949e+06,NaN,NaN,NaN,NaN,NaN
48984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.657962e+06,1.662547e+06,NaN,NaN,NaN,NaN,NaN
51061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.687670e+06,2.699301e+06,NaN,NaN,NaN,NaN,NaN
51063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.554948e+03,1.466010e+03,NaN,NaN,NaN,NaN,NaN
53240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.730455e+06,2.737188e+06,NaN,NaN,NaN,NaN,NaN
53245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.191829e+03,2.183376e+03,NaN,NaN,NaN,NaN,NaN
55039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.199567e+06,2.204542e+06,NaN,NaN,NaN,NaN,NaN
55042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.046738e+02,8.156400e+01,NaN,NaN,NaN,NaN,NaN
57888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.340792e+06,3.314519e+06,NaN,NaN,NaN,NaN,NaN
57891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.480582e+02,7.557840e+02,NaN,NaN,NaN,NaN,NaN
60894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.430306e+06,3.415479e+06,NaN,NaN,NaN,NaN,NaN
60895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.998011e+07,8.045060e+07,NaN,NaN,NaN,NaN,NaN

In [ ]:
before_rows = len(fact_reseller_sales)

fact_reseller_sales = fact_reseller_sales[
    fact_reseller_sales["ProductKey"].notna()
    & fact_reseller_sales["ResellerKey"].notna()
    & fact_reseller_sales["EmployeeKey"].notna()
    & fact_reseller_sales["SalesTerritoryKey"].notna()
    & fact_reseller_sales["SalesOrderNumber"].notna()
    & fact_reseller_sales["OrderDate"].notna()
].reset_index(drop=True)

after_rows = len(fact_reseller_sales)

print("Rows before FK cleaning:", before_rows)
print("Invalid/incomplete rows removed:", before_rows - after_rows)
print("Rows after FK cleaning:", after_rows)

Rows before FK cleaning: 60896
Invalid/incomplete rows removed: 41
Rows after FK cleaning: 60855

In [ ]:
date_columns = {
    "FactInternetSales": ["OrderDate", "DueDate", "ShipDate"],
    "FactResellerSales": ["OrderDate", "DueDate", "ShipDate"]
}

for table_name, columns in date_columns.items():
    df = tables[table_name] if table_name == "FactInternetSales" else fact_reseller_sales

    print("=" * 70)
    print(table_name)
    print("=" * 70)

    for col in columns:
        dates = pd.to_datetime(df[col], errors="coerce")

        print(f"{col}:")
        print("  Invalid dates:", dates.isna().sum())
        print("  Minimum date:", dates.min())
        print("  Maximum date:", dates.max())

    print()

======================================================================
FactInternetSales
======================================================================
OrderDate:
  Invalid dates: 0
  Minimum date: 2010-12-29 00:00:00
  Maximum date: 2014-01-28 00:00:00
DueDate:
  Invalid dates: 0
  Minimum date: 2011-01-10 00:00:00
  Maximum date: 2014-02-09 00:00:00
ShipDate:
  Invalid dates: 0
  Minimum date: 2011-01-05 00:00:00
  Maximum date: 2014-02-04 00:00:00

======================================================================
FactResellerSales
======================================================================
OrderDate:
  Invalid dates: 0
  Minimum date: 2010-12-29 00:00:00
  Maximum date: 2013-11-29 00:00:00
DueDate:
  Invalid dates: 0
  Minimum date: 2011-01-10 00:00:00
  Maximum date: 2013-12-11 00:00:00
ShipDate:
  Invalid dates: 0
  Minimum date: 2011-01-05 00:00:00
  Maximum date: 2013-12-06 00:00:00

In [ ]:
fact_internet_sales["OrderDate"] = pd.to_datetime(
    fact_internet_sales["OrderDate"], errors="coerce"
)
fact_internet_sales["DueDate"] = pd.to_datetime(
    fact_internet_sales["DueDate"], errors="coerce"
)
fact_internet_sales["ShipDate"] = pd.to_datetime(
    fact_internet_sales["ShipDate"], errors="coerce"
)

fact_reseller_sales["OrderDate"] = pd.to_datetime(
    fact_reseller_sales["OrderDate"], errors="coerce"
)
fact_reseller_sales["DueDate"] = pd.to_datetime(
    fact_reseller_sales["DueDate"], errors="coerce"
)
fact_reseller_sales["ShipDate"] = pd.to_datetime(
    fact_reseller_sales["ShipDate"], errors="coerce"
)

print("Internet Sales date columns converted successfully.")
print("Reseller Sales date columns converted successfully.")

print("\nInternet Sales:")
print(fact_internet_sales[["OrderDate", "DueDate", "ShipDate"]].dtypes)

print("\nReseller Sales:")
print(fact_reseller_sales[["OrderDate", "DueDate", "ShipDate"]].dtypes)

Internet Sales date columns converted successfully.
Reseller Sales date columns converted successfully.

Internet Sales:
OrderDate    datetime64[ns]
DueDate      datetime64[ns]
ShipDate     datetime64[ns]
dtype: object

Reseller Sales:
OrderDate    datetime64[ns]
DueDate      datetime64[ns]
ShipDate     datetime64[ns]
dtype: object

In [ ]:
numeric_checks = {
    "FactInternetSales": [
        "DiscountAmount",
        "TotalProductCost",
        "SalesAmount",
        "Freight"
    ],
    "FactResellerSales": [
        "DiscountAmount",
        "TotalProductCost",
        "SalesAmount",
        "Freight"
    ]
}

for table_name, columns in numeric_checks.items():
    df = fact_internet_sales if table_name == "FactInternetSales" else fact_reseller_sales

    print("=" * 70)
    print(table_name)
    print("=" * 70)

    for col in columns:
        print(f"{col}:")
        print("  Missing:", df[col].isna().sum())
        print("  Negative values:", (df[col] < 0).sum())
        print("  Minimum:", df[col].min())
        print("  Maximum:", df[col].max())

    print()

======================================================================
FactInternetSales
======================================================================
DiscountAmount:
  Missing: 0
  Negative values: 0
  Minimum: 0
  Maximum: 0
TotalProductCost:
  Missing: 0
  Negative values: 0
  Minimum: 0.8565
  Maximum: 2171.2942
SalesAmount:
  Missing: 0
  Negative values: 0
  Minimum: 2.29
  Maximum: 3578.27
Freight:
  Missing: 0
  Negative values: 0
  Minimum: 0.0573
  Maximum: 89.4568

======================================================================
FactResellerSales
======================================================================
DiscountAmount:
  Missing: 0
  Negative values: 0
  Minimum: 0.0
  Maximum: 4005.23759999999
TotalProductCost:
  Missing: 0
  Negative values: 0
  Minimum: 0.8565
  Maximum: 38530.3854
SalesAmount:
  Missing: 0
  Negative values: 0
  Minimum: 1.374
  Maximum: 27893.619
Freight:
  Missing: 0
  Negative values: 0
  Minimum: 0.0344
  Maximum: 697.3405

In [ ]:
categorical_checks = {
    "FactInternetSales": [
        "ProductKey",
        "CustomerKey",
        "SalesTerritoryKey",
        "SalesOrderNumber"
    ],
    "FactResellerSales": [
        "ProductKey",
        "ResellerKey",
        "EmployeeKey",
        "SalesTerritoryKey",
        "SalesOrderNumber"
    ]
}

for table_name, columns in categorical_checks.items():
    df = fact_internet_sales if table_name == "FactInternetSales" else fact_reseller_sales

    print("=" * 70)
    print(table_name)
    print("=" * 70)

    for col in columns:
        print(f"{col}:")
        print("  Missing:", df[col].isna().sum())
        print("  Unique values:", df[col].nunique())

    print()

======================================================================
FactInternetSales
======================================================================
ProductKey:
  Missing: 0
  Unique values: 158
CustomerKey:
  Missing: 0
  Unique values: 18484
SalesTerritoryKey:
  Missing: 0
  Unique values: 10
SalesOrderNumber:
  Missing: 0
  Unique values: 27659

======================================================================
FactResellerSales
======================================================================
ProductKey:
  Missing: 0
  Unique values: 334
ResellerKey:
  Missing: 0
  Unique values: 635
EmployeeKey:
  Missing: 0
  Unique values: 17
SalesTerritoryKey:
  Missing: 0
  Unique values: 10
SalesOrderNumber:
  Missing: 0
  Unique values: 3796

In [ ]:
for table_name, df in {
    "FactInternetSales": fact_internet_sales,
    "FactResellerSales": fact_reseller_sales
}.items():

    print("=" * 70)
    print(table_name)
    print("=" * 70)

    order_line_check = df.groupby("SalesOrderNumber")["SalesOrderLineNumber"].nunique()

    print("Total orders:", df["SalesOrderNumber"].nunique())
    print("Orders with 1 line:", (order_line_check == 1).sum())
    print("Orders with multiple lines:", (order_line_check > 1).sum())
    print("Maximum lines in one order:", order_line_check.max())
    print()

======================================================================
FactInternetSales
======================================================================
Total orders: 27659
Orders with 1 line: 9668
Orders with multiple lines: 17991
Maximum lines in one order: 8

======================================================================
FactResellerSales
======================================================================
Total orders: 3796
Orders with 1 line: 582
Orders with multiple lines: 3214
Maximum lines in one order: 72

In [ ]:
for table_name, df in {
    "FactInternetSales": fact_internet_sales,
    "FactResellerSales": fact_reseller_sales
}.items():

    duplicate_order_lines = df.duplicated(
        subset=["SalesOrderNumber", "SalesOrderLineNumber"]
    ).sum()

    print("=" * 70)
    print(table_name)
    print("=" * 70)
    print("Duplicate SalesOrderNumber + SalesOrderLineNumber:", duplicate_order_lines)
    print()

======================================================================
FactInternetSales
======================================================================
Duplicate SalesOrderNumber + SalesOrderLineNumber: 0

======================================================================
FactResellerSales
======================================================================
Duplicate SalesOrderNumber + SalesOrderLineNumber: 0

In [ ]:
final_tables = {
    "DimCustomer": dim_customer,
    "DimEmployee": dim_employee,
    "DimGeography": dim_geography,
    "DimProduct": dim_product,
    "DimReseller": dim_reseller,
    "DimSalesTerritory": dim_sales_territory,
    "FactInternetSales": fact_internet_sales,
    "FactResellerSales": fact_reseller_sales
}

print("=" * 80)
print("FINAL DATA QUALITY SUMMARY")
print("=" * 80)

for name, df in final_tables.items():
    print(f"\n{name}")
    print("-" * 50)
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Missing values:", df.isnull().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())

print("\n" + "=" * 80)
print("DATA QUALITY VALIDATION COMPLETED")
print("=" * 80)

================================================================================
FINAL DATA QUALITY SUMMARY
================================================================================

DimCustomer
--------------------------------------------------
Rows: 18484
Columns: 13
Missing values: 0
Duplicate rows: 0

DimEmployee
--------------------------------------------------
Rows: 21
Columns: 9
Missing values: 1
Duplicate rows: 0

DimGeography
--------------------------------------------------
Rows: 655
Columns: 6
Missing values: 0
Duplicate rows: 0

DimProduct
--------------------------------------------------
Rows: 397
Columns: 7
Missing values: 56
Duplicate rows: 0

DimReseller
--------------------------------------------------
Rows: 701
Columns: 4
Missing values: 0
Duplicate rows: 0

DimSalesTerritory
--------------------------------------------------
Rows: 11
Columns: 4
Missing values: 3
Duplicate rows: 0

FactInternetSales
--------------------------------------------------
Rows: 60398
Columns: 13
Missing values: 60398
Duplicate rows: 0

FactResellerSales
--------------------------------------------------
Rows: 60855
Columns: 14
Missing values: 0
Duplicate rows: 0

================================================================================
DATA QUALITY VALIDATION COMPLETED
================================================================================

In [ ]:
dimension_missing = {
    "DimEmployee": dim_employee,
    "DimProduct": dim_product,
    "DimSalesTerritory": dim_sales_territory
}

for name, df in dimension_missing.items():
    print("=" * 80)
    print(name)
    print("=" * 80)

    missing_cols = df.columns[df.isnull().any()]

    for col in missing_cols:
        print(f"\nColumn: {col}")
        print("Missing values:", df[col].isnull().sum())
        display(df[df[col].isnull()])

================================================================================
DimEmployee
================================================================================

Column: ParentEmployeeKey
Missing values: 1

,EmployeeKey,ParentEmployeeKey,SalesTerritoryKey,EmployeeName,Title,EmailAddress,DepartmentName,HireDate,BirthDate
0,112,NaN,11,Ken Sánchez,Chief Executive Officer,ken0@adventure-works.com,Executive,2008-08-14,1968-08-29

================================================================================
DimProduct
================================================================================

Column: Color
Missing values: 56

,ProductKey,ProductSubcategoryKey,Product,Color,Model,Subcategory,Category
12,391,10,LL Fork,NaN,LL Fork,Forks,Components
13,392,10,ML Fork,NaN,ML Fork,Forks,Components
14,393,10,HL Fork,NaN,HL Fork,Forks,Components
15,397,4,LL Mountain Handlebars,NaN,LL Mountain Handlebars,Handlebars,Components
16,398,4,LL Mountain Handlebars,NaN,LL Mountain Handlebars,Handlebars,Components
26,447,34,Cable Lock,NaN,Cable Lock,Locks,Accessories
27,448,36,Minipump,NaN,Minipump,Pumps,Accessories
28,449,36,Mountain Pump,NaN,Mountain Pump,Pumps,Accessories
29,450,33,Taillights - Battery-Powered,NaN,Taillight,Lights,Accessories
30,451,33,Headlights - Dual-Beam,NaN,Headlights - Dual-Beam,Lights,Accessories
31,452,33,Headlights - Weatherproof,NaN,Headlights - Weatherproof,Lights,Accessories
38,477,28,Water Bottle - 30 oz.,NaN,Water Bottle,Bottles and Cages,Accessories
39,479,28,Road Bottle Cage,NaN,Road Bottle Cage,Bottles and Cages,Accessories
40,480,37,Patch Kit/8 Patches,NaN,Patch kit,Tires and Tubes,Accessories
45,515,15,LL Mountain Seat/Saddle,NaN,LL Mountain Seat/Saddle 2,Saddles,Components
46,530,37,Touring Tire Tube,NaN,Touring Tire Tube,Tires and Tubes,Accessories
47,537,37,HL Mountain Tire,NaN,HL Mountain Tire,Tires and Tubes,Accessories
48,540,37,HL Road Tire,NaN,HL Road Tire,Tires and Tubes,Accessories
65,394,11,LL Headset,NaN,LL Headset,Headsets,Components
66,395,11,ML Headset,NaN,ML Headset,Headsets,Components
67,396,11,HL Headset,NaN,HL Headset,Headsets,Components
68,399,4,ML Mountain Handlebars,NaN,ML Mountain Handlebars,Handlebars,Components
69,400,4,ML Mountain Handlebars,NaN,ML Mountain Handlebars,Handlebars,Components
70,401,4,HL Mountain Handlebars,NaN,HL Mountain Handlebars,Handlebars,Components
71,402,4,HL Mountain Handlebars,NaN,HL Mountain Handlebars,Handlebars,Components
72,403,4,LL Road Handlebars,NaN,LL Road Handlebars,Handlebars,Components
73,404,4,LL Road Handlebars,NaN,LL Road Handlebars,Handlebars,Components
74,405,4,ML Road Handlebars,NaN,ML Road Handlebars,Handlebars,Components
75,406,4,ML Road Handlebars,NaN,ML Road Handlebars,Handlebars,Components
76,407,4,HL Road Handlebars,NaN,HL Road Handlebars,Handlebars,Components
77,408,4,HL Road Handlebars,NaN,HL Road Handlebars,Handlebars,Components
97,478,28,Mountain Bottle Cage,NaN,Mountain Bottle Cage,Bottles and Cages,Accessories
100,483,26,Hitch Rack - 4-Bike,NaN,Hitch Rack - 4-Bike,Bike Racks,Accessories
101,484,29,Bike Wash - Dissolver,NaN,Bike Wash,Cleaners,Accessories
102,485,30,Fender Set - Mountain,NaN,Fender Set - Mountain,Fenders,Accessories
103,486,27,All-Purpose Bike Stand,NaN,All-Purpose Bike Stand,Bike Stands,Accessories
105,516,15,ML Mountain Seat/Saddle,NaN,ML Mountain Seat/Saddle 2,Saddles,Components
106,517,15,HL Mountain Seat/Saddle,NaN,HL Mountain Seat/Saddle 2,Saddles,Components
107,518,15,LL Road Seat/Saddle,NaN,LL Road Seat/Saddle 1,Saddles,Components
108,519,15,ML Road Seat/Saddle,NaN,ML Road Seat/Saddle 2,Saddles,Components
109,520,15,HL Road Seat/Saddle,NaN,HL Road Seat/Saddle 2,Saddles,Components
110,521,15,LL Touring Seat/Saddle,NaN,LL Touring Seat/Saddle,Saddles,Components
111,522,15,ML Touring Seat/Saddle,NaN,ML Touring Seat/Saddle,Saddles,Components
112,523,15,HL Touring Seat/Saddle,NaN,HL Touring Seat/Saddle,Saddles,Components
113,528,37,Mountain Tire Tube,NaN,Mountain Tire Tube,Tires and Tubes,Accessories
114,529,37,Road Tire Tube,NaN,Road Tire Tube,Tires and Tubes,Accessories
115,535,37,LL Mountain Tire,NaN,LL Mountain Tire,Tires and Tubes,Accessories
116,536,37,ML Mountain Tire,NaN,ML Mountain Tire,Tires and Tubes,Accessories
117,538,37,LL Road Tire,NaN,LL Road Tire,Tires and Tubes,Accessories
118,539,37,ML Road Tire,NaN,ML Road Tire,Tires and Tubes,Accessories
119,541,37,Touring Tire,NaN,Touring Tire,Tires and Tubes,Accessories
120,553,4,LL Touring Handlebars,NaN,LL Touring Handlebars,Handlebars,Components
121,554,4,HL Touring Handlebars,NaN,HL Touring Handlebars,Handlebars,Components
384,601,5,LL Bottom Bracket,NaN,LL Bottom Bracket,Bottom Brackets,Components
385,602,5,ML Bottom Bracket,NaN,ML Bottom Bracket,Bottom Brackets,Components
386,603,5,HL Bottom Bracket,NaN,HL Bottom Bracket,Bottom Brackets,Components

================================================================================
DimSalesTerritory
================================================================================

Column: SalesTerritoryRegion
Missing values: 1

,SalesTerritoryKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
10,11,NaN,NaN,NaN

Column: SalesTerritoryCountry
Missing values: 1

,SalesTerritoryKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
10,11,NaN,NaN,NaN

Column: SalesTerritoryGroup
Missing values: 1

,SalesTerritoryKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
10,11,NaN,NaN,NaN

In [ ]:
# DimEmployee
# CEO has no parent employee, so this missing value is intentionally retained.
print("DimEmployee: ParentEmployeeKey missing value retained for top-level CEO.")

# DimProduct
dim_product["Color"] = dim_product["Color"].fillna("Unknown")

# DimSalesTerritory
territory_cols = [
    "SalesTerritoryRegion",
    "SalesTerritoryCountry",
    "SalesTerritoryGroup"
]

for col in territory_cols:
    dim_sales_territory[col] = dim_sales_territory[col].fillna("Unknown")

print("\nMissing values after treatment:")
print("DimEmployee:", dim_employee.isnull().sum().sum())
print("DimProduct:", dim_product.isnull().sum().sum())
print("DimSalesTerritory:", dim_sales_territory.isnull().sum().sum())

DimEmployee: ParentEmployeeKey missing value retained for top-level CEO.

Missing values after treatment:
DimEmployee: 1
DimProduct: 0
DimSalesTerritory: 0

In [ ]:
# Create cleaned copies for ETL
dim_customer_clean = dim_customer.copy()
dim_employee_clean = dim_employee.copy()
dim_geography_clean = dim_geography.copy()
dim_product_clean = dim_product.copy()
dim_reseller_clean = dim_reseller.copy()
dim_sales_territory_clean = dim_sales_territory.copy()

fact_internet_sales_clean = fact_internet_sales.copy()
fact_reseller_sales_clean = fact_reseller_sales.copy()

print("Cleaned ETL DataFrames created successfully.")

print("\nFinal row counts:")
for name, df in {
    "DimCustomer": dim_customer_clean,
    "DimEmployee": dim_employee_clean,
    "DimGeography": dim_geography_clean,
    "DimProduct": dim_product_clean,
    "DimReseller": dim_reseller_clean,
    "DimSalesTerritory": dim_sales_territory_clean,
    "FactInternetSales": fact_internet_sales_clean,
    "FactResellerSales": fact_reseller_sales_clean
}.items():
    print(f"{name}: {len(df)} rows")

Cleaned ETL DataFrames created successfully.

Final row counts:
DimCustomer: 18484 rows
DimEmployee: 21 rows
DimGeography: 655 rows
DimProduct: 397 rows
DimReseller: 701 rows
DimSalesTerritory: 11 rows
FactInternetSales: 60398 rows
FactResellerSales: 60855 rows

In [ ]:
clean_tables = {
    "DimCustomer": dim_customer_clean,
    "DimEmployee": dim_employee_clean,
    "DimGeography": dim_geography_clean,
    "DimProduct": dim_product_clean,
    "DimReseller": dim_reseller_clean,
    "DimSalesTerritory": dim_sales_territory_clean,
    "FactInternetSales": fact_internet_sales_clean,
    "FactResellerSales": fact_reseller_sales_clean
}

for name, df in clean_tables.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    print("Shape:", df.shape)
    print("Columns:")
    print(list(df.columns))
    print()

================================================================================
DimCustomer
================================================================================
Shape: (18484, 13)
Columns:
['CustomerKey', 'GeographyKey', 'CustomerName', 'BirthDate', 'MaritalStatus', 'Gender', 'EmailAddress', 'YearlyIncome', 'Education', 'Occupation', 'HouseOwnerFlag', 'Address', 'FirstPurchaseDate']

================================================================================
DimEmployee
================================================================================
Shape: (21, 9)
Columns:
['EmployeeKey', 'ParentEmployeeKey', 'SalesTerritoryKey', 'EmployeeName', 'Title', 'EmailAddress', 'DepartmentName', 'HireDate', 'BirthDate']

================================================================================
DimGeography
================================================================================
Shape: (655, 6)
Columns:
['GeographyKey', 'City', 'State', 'Country', 'PostalCode', 'SalesTerritoryKey']

================================================================================
DimProduct
================================================================================
Shape: (397, 7)
Columns:
['ProductKey', 'ProductSubcategoryKey', 'Product', 'Color', 'Model', 'Subcategory', 'Category']

================================================================================
DimReseller
================================================================================
Shape: (701, 4)
Columns:
['ResellerKey', 'GeographyKey', 'BusinessType', 'ResellerName']

================================================================================
DimSalesTerritory
================================================================================
Shape: (11, 4)
Columns:
['SalesTerritoryKey', 'SalesTerritoryRegion', 'SalesTerritoryCountry', 'SalesTerritoryGroup']

================================================================================
FactInternetSales
================================================================================
Shape: (60398, 13)
Columns:
['ProductKey', 'CustomerKey', 'SalesTerritoryKey', 'SalesOrderNumber', 'SalesOrderLineNumber', 'DiscountAmount', 'TotalProductCost', 'SalesAmount', 'Freight', 'CarrierTrackingNumber', 'OrderDate', 'DueDate', 'ShipDate']

================================================================================
FactResellerSales
================================================================================
Shape: (60855, 14)
Columns:
['ProductKey', 'ResellerKey', 'EmployeeKey', 'SalesTerritoryKey', 'SalesOrderNumber', 'SalesOrderLineNumber', 'DiscountAmount', 'TotalProductCost', 'SalesAmount', 'Freight', 'CarrierTrackingNumber', 'OrderDate', 'DueDate', 'ShipDate']

In [ ]:
# Standardize integer columns
integer_columns = {
    "DimCustomer": ["CustomerKey", "GeographyKey", "YearlyIncome", "HouseOwnerFlag"],
    "DimEmployee": ["EmployeeKey", "SalesTerritoryKey"],
    "DimGeography": ["GeographyKey", "SalesTerritoryKey"],
    "DimProduct": ["ProductKey", "ProductSubcategoryKey"],
    "DimReseller": ["ResellerKey", "GeographyKey"],
    "DimSalesTerritory": ["SalesTerritoryKey"],
    "FactInternetSales": ["ProductKey", "CustomerKey", "SalesTerritoryKey", "SalesOrderLineNumber"],
    "FactResellerSales": ["ProductKey", "ResellerKey", "EmployeeKey", "SalesTerritoryKey", "SalesOrderLineNumber"]
}

for table_name, columns in integer_columns.items():
    df = clean_tables[table_name]

    for col in columns:
        if col in df.columns:
            # Nullable integer type is used where necessary
            df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

# Standardize date columns
date_columns = {
    "DimCustomer": ["BirthDate", "FirstPurchaseDate"],
    "DimEmployee": ["HireDate", "BirthDate"],
    "FactInternetSales": ["OrderDate", "DueDate", "ShipDate"],
    "FactResellerSales": ["OrderDate", "DueDate", "ShipDate"]
}

for table_name, columns in date_columns.items():
    df = clean_tables[table_name]

    for col in columns:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

print("Data types standardized successfully.")

print("\nFactInternetSales date types:")
print(fact_internet_sales_clean[["OrderDate", "DueDate", "ShipDate"]].dtypes)

print("\nFactResellerSales date types:")
print(fact_reseller_sales_clean[["OrderDate", "DueDate", "ShipDate"]].dtypes)

Data types standardized successfully.

FactInternetSales date types:
OrderDate    datetime64[ns]
DueDate      datetime64[ns]
ShipDate     datetime64[ns]
dtype: object

FactResellerSales date types:
OrderDate    datetime64[ns]
DueDate      datetime64[ns]
ShipDate     datetime64[ns]
dtype: object

In [ ]:
# Determine the reference date from both sales channels
internet_max_date = fact_internet_sales_clean["OrderDate"].max()
reseller_max_date = fact_reseller_sales_clean["OrderDate"].max()

reference_date = max(internet_max_date, reseller_max_date)

# Calculate age using a vectorized method
dim_customer_clean["Age"] = (
    reference_date.year
    - dim_customer_clean["BirthDate"].dt.year
    - (
        (
            dim_customer_clean["BirthDate"].dt.month > reference_date.month
        )
        |
        (
            (dim_customer_clean["BirthDate"].dt.month == reference_date.month)
            & (dim_customer_clean["BirthDate"].dt.day > reference_date.day)
        )
    ).astype(int)
)

# Create age groups for marketing analysis
def assign_age_group(age):
    if age < 25:
        return "<25"
    elif age < 30:
        return "25-30"
    elif age < 35:
        return "30-35"
    elif age < 40:
        return "35-40"
    elif age < 45:
        return "40-45"
    elif age < 50:
        return "45-50"
    else:
        return "50+"

dim_customer_clean["AgeGroup"] = dim_customer_clean["Age"].apply(assign_age_group)

print("Reference Date:", reference_date.date())

print("\nAge statistics:")
print(dim_customer_clean["Age"].describe())

print("\nCustomer count by Age Group:")
print(
    dim_customer_clean["AgeGroup"]
    .value_counts()
    .sort_index()
)

print("\nAge columns added successfully.")

print(
    dim_customer_clean[
        ["CustomerKey", "BirthDate", "Age", "AgeGroup"]
    ].head(10)
)

Reference Date: 2014-01-28

Age statistics:
count    18484.000000
mean        44.250433
std         11.536420
min         27.000000
25%         35.000000
50%         42.000000
75%         52.000000
max         97.000000
Name: Age, dtype: float64

Customer count by Age Group:
AgeGroup
25-30    1129
30-35    3199
35-40    3255
40-45    3006
45-50    2282
50+      5613
Name: count, dtype: int64

Age columns added successfully.
   CustomerKey  BirthDate  Age AgeGroup
0        11000 1971-10-06   42    40-45
1        11001 1976-05-10   37    35-40
2        11002 1971-02-09   42    40-45
3        11003 1973-08-14   40    40-45
4        11004 1979-08-05   34    30-35
5        11005 1976-08-01   37    35-40
6        11006 1976-12-02   37    35-40
7        11007 1969-11-06   44    40-45
8        11008 1975-07-04   38    35-40
9        11009 1969-09-29   44    40-45

In [ ]:
# Get the complete sales date range from both fact tables
min_date = min(
    fact_internet_sales_clean["OrderDate"].min(),
    fact_reseller_sales_clean["OrderDate"].min()
)

max_date = max(
    fact_internet_sales_clean["OrderDate"].max(),
    fact_reseller_sales_clean["OrderDate"].max()
)

# Create continuous date range
date_range = pd.date_range(
    start=min_date,
    end=max_date,
    freq="D"
)

# Create Date Dimension
dim_date = pd.DataFrame({
    "Date": date_range
})

# Date attributes
dim_date["Year"] = dim_date["Date"].dt.year
dim_date["Quarter"] = "Q" + dim_date["Date"].dt.quarter.astype(str)
dim_date["MonthNumber"] = dim_date["Date"].dt.month
dim_date["MonthName"] = dim_date["Date"].dt.month_name()
dim_date["YearMonth"] = dim_date["Date"].dt.strftime("%Y-%m")
dim_date["Day"] = dim_date["Date"].dt.day
dim_date["DayName"] = dim_date["Date"].dt.day_name()
dim_date["WeekNumber"] = dim_date["Date"].dt.isocalendar().week.astype(int)

print("Date Dimension created successfully.")
print("Date Range:", dim_date["Date"].min().date(), "to", dim_date["Date"].max().date())
print("Total Dates:", len(dim_date))

print("\nColumns:")
print(list(dim_date.columns))

print("\nSample records:")
print(dim_date.head())

print("\nYear-wise date count:")
print(dim_date.groupby("Year")["Date"].count())

Date Dimension created successfully.
Date Range: 2010-12-29 to 2014-01-28
Total Dates: 1127

Columns:
['Date', 'Year', 'Quarter', 'MonthNumber', 'MonthName', 'YearMonth', 'Day', 'DayName', 'WeekNumber']

Sample records:
        Date  Year Quarter  MonthNumber MonthName YearMonth  Day    DayName  \
0 2010-12-29  2010      Q4           12  December   2010-12   29  Wednesday
1 2010-12-30  2010      Q4           12  December   2010-12   30   Thursday
2 2010-12-31  2010      Q4           12  December   2010-12   31     Friday
3 2011-01-01  2011      Q1            1   January   2011-01    1   Saturday
4 2011-01-02  2011      Q1            1   January   2011-01    2     Sunday

   WeekNumber
0          52
1          52
2          52
3          52
4          52

Year-wise date count:
Year
2010      3
2011    365
2012    366
2013    365
2014     28
Name: Date, dtype: int64

In [ ]:
# Add sales channel to distinguish the two sales sources

fact_internet_sales_clean["SalesChannel"] = "Internet"
fact_reseller_sales_clean["SalesChannel"] = "Reseller"

print("Sales Channel added successfully.")

print("\nInternet Sales:")
print(fact_internet_sales_clean["SalesChannel"].value_counts())

print("\nReseller Sales:")
print(fact_reseller_sales_clean["SalesChannel"].value_counts())

print("\nUpdated FactInternetSales shape:", fact_internet_sales_clean.shape)
print("Updated FactResellerSales shape:", fact_reseller_sales_clean.shape)

Sales Channel added successfully.

Internet Sales:
SalesChannel
Internet    60398
Name: count, dtype: int64

Reseller Sales:
SalesChannel
Reseller    60855
Name: count, dtype: int64

Updated FactInternetSales shape: (60398, 14)
Updated FactResellerSales shape: (60855, 15)

In [ ]:
# Select common columns from both sales fact tables
common_columns = [
    "ProductKey",
    "SalesTerritoryKey",
    "SalesOrderNumber",
    "SalesOrderLineNumber",
    "DiscountAmount",
    "TotalProductCost",
    "SalesAmount",
    "Freight",
    "CarrierTrackingNumber",
    "OrderDate",
    "DueDate",
    "ShipDate",
    "SalesChannel"
]

# Add CustomerKey for Internet Sales
internet_combined = fact_internet_sales_clean[
    common_columns[:]
].copy()

internet_combined["CustomerKey"] = fact_internet_sales_clean["CustomerKey"]
internet_combined["ResellerKey"] = pd.NA
internet_combined["EmployeeKey"] = pd.NA

# Add ResellerKey and EmployeeKey for Reseller Sales
reseller_combined = fact_reseller_sales_clean[
    common_columns[:]
].copy()

reseller_combined["CustomerKey"] = pd.NA
reseller_combined["ResellerKey"] = fact_reseller_sales_clean["ResellerKey"]
reseller_combined["EmployeeKey"] = fact_reseller_sales_clean["EmployeeKey"]

# Reorder columns
combined_columns = [
    "ProductKey",
    "CustomerKey",
    "ResellerKey",
    "EmployeeKey",
    "SalesTerritoryKey",
    "SalesOrderNumber",
    "SalesOrderLineNumber",
    "DiscountAmount",
    "TotalProductCost",
    "SalesAmount",
    "Freight",
    "CarrierTrackingNumber",
    "OrderDate",
    "DueDate",
    "ShipDate",
    "SalesChannel"
]

# Combine both channels
fact_sales = pd.concat(
    [
        internet_combined[combined_columns],
        reseller_combined[combined_columns]
    ],
    ignore_index=True
)

print("Combined Fact Sales created successfully.")
print("Shape:", fact_sales.shape)

print("\nSales Channel distribution:")
print(fact_sales["SalesChannel"].value_counts())

print("\nColumns:")
print(list(fact_sales.columns))

print("\nSample records:")
print(fact_sales.head())

/tmp/ipykernel_3354/1800248.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  fact_sales = pd.concat(

Combined Fact Sales created successfully.
Shape: (121253, 16)

Sales Channel distribution:
SalesChannel
Reseller    60855
Internet    60398
Name: count, dtype: int64

Columns:
['ProductKey', 'CustomerKey', 'ResellerKey', 'EmployeeKey', 'SalesTerritoryKey', 'SalesOrderNumber', 'SalesOrderLineNumber', 'DiscountAmount', 'TotalProductCost', 'SalesAmount', 'Freight', 'CarrierTrackingNumber', 'OrderDate', 'DueDate', 'ShipDate', 'SalesChannel']

Sample records:
   ProductKey  CustomerKey  ResellerKey  EmployeeKey  SalesTerritoryKey  \
0         310        21768         <NA>         <NA>                  6
1         346        28389         <NA>         <NA>                  7
2         346        25863         <NA>         <NA>                  1
3         336        14501         <NA>         <NA>                  4
4         346        11003         <NA>         <NA>                  9

  SalesOrderNumber  SalesOrderLineNumber  DiscountAmount  TotalProductCost  \
0          SO43697                     1             0.0         2171.2942
1          SO43698                     1             0.0         1912.1544
2          SO43699                     1             0.0         1912.1544
3          SO43700                     1             0.0          413.1463
4          SO43701                     1             0.0         1912.1544

   SalesAmount  Freight CarrierTrackingNumber  OrderDate    DueDate  \
0    3578.2700  89.4568                   NaN 2010-12-29 2011-01-10
1    3399.9900  84.9998                   NaN 2010-12-29 2011-01-10
2    3399.9900  84.9998                   NaN 2010-12-29 2011-01-10
3     699.0982  17.4775                   NaN 2010-12-29 2011-01-10
4    3399.9900  84.9998                   NaN 2010-12-29 2011-01-10

    ShipDate SalesChannel
0 2011-01-05     Internet
1 2011-01-05     Internet
2 2011-01-05     Internet
3 2011-01-05     Internet
4 2011-01-05     Internet

In [ ]:
print("=" * 80)
print("COMBINED FACT SALES VALIDATION")
print("=" * 80)

# 1. Missing values
print("\nMissing Values:")
print(fact_sales.isnull().sum())

# 2. Duplicate order lines
duplicate_order_lines = fact_sales.duplicated(
    subset=["SalesOrderNumber", "SalesOrderLineNumber"],
    keep=False
).sum()

print("\nDuplicate Order Lines:", duplicate_order_lines)

# 3. Negative values
numeric_check = {
    "DiscountAmount": (fact_sales["DiscountAmount"] < 0).sum(),
    "TotalProductCost": (fact_sales["TotalProductCost"] < 0).sum(),
    "SalesAmount": (fact_sales["SalesAmount"] < 0).sum(),
    "Freight": (fact_sales["Freight"] < 0).sum()
}

print("\nNegative Value Check:")
for column, count in numeric_check.items():
    print(f"{column}: {count}")

# 4. Sales channel counts
print("\nSales Channel Counts:")
print(fact_sales["SalesChannel"].value_counts())

# 5. Date range
print("\nSales Date Range:")
print("Minimum:", fact_sales["OrderDate"].min().date())
print("Maximum:", fact_sales["OrderDate"].max().date())

# 6. Final row count
print("\nFinal Fact Sales Rows:", len(fact_sales))

================================================================================
COMBINED FACT SALES VALIDATION
================================================================================

Missing Values:
ProductKey                   0
CustomerKey              60855
ResellerKey              60398
EmployeeKey              60398
SalesTerritoryKey            0
SalesOrderNumber             0
SalesOrderLineNumber         0
DiscountAmount               0
TotalProductCost             0
SalesAmount                  0
Freight                      0
CarrierTrackingNumber    60398
OrderDate                    0
DueDate                      0
ShipDate                     0
SalesChannel                 0
dtype: int64

Duplicate Order Lines: 0

Negative Value Check:
DiscountAmount: 0
TotalProductCost: 0
SalesAmount: 0
Freight: 0

Sales Channel Counts:
SalesChannel
Reseller    60855
Internet    60398
Name: count, dtype: int64

Sales Date Range:
Minimum: 2010-12-29
Maximum: 2014-01-28

Final Fact Sales Rows: 121253

In [ ]:
# Create the final ETL-ready table collection

etl_tables = {
    "dim_customer": dim_customer_clean,
    "dim_employee": dim_employee_clean,
    "dim_geography": dim_geography_clean,
    "dim_product": dim_product_clean,
    "dim_reseller": dim_reseller_clean,
    "dim_sales_territory": dim_sales_territory_clean,
    "dim_date": dim_date,
    "fact_internet_sales": fact_internet_sales_clean,
    "fact_reseller_sales": fact_reseller_sales_clean,
    "fact_sales": fact_sales
}

print("=" * 80)
print("FINAL ETL TABLE SUMMARY")
print("=" * 80)

for table_name, df in etl_tables.items():
    print(f"{table_name:<25} {df.shape[0]:>8} rows × {df.shape[1]:>3} columns")

print("\nTotal tables prepared:", len(etl_tables))

================================================================================
FINAL ETL TABLE SUMMARY
================================================================================
dim_customer                 18484 rows ×  15 columns
dim_employee                    21 rows ×   9 columns
dim_geography                  655 rows ×   6 columns
dim_product                    397 rows ×   7 columns
dim_reseller                   701 rows ×   4 columns
dim_sales_territory             11 rows ×   4 columns
dim_date                      1127 rows ×   9 columns
fact_internet_sales          60398 rows ×  14 columns
fact_reseller_sales          60855 rows ×  15 columns
fact_sales                  121253 rows ×  16 columns

Total tables prepared: 10

In [ ]:
print("=" * 80)
print("FINAL ETL DATA QUALITY CHECK")
print("=" * 80)

for table_name, df in etl_tables.items():
    print(f"\n{table_name}")
    print("-" * 50)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicate rows:", df.duplicated().sum())
    print("Missing values:", df.isnull().sum().sum())

print("\n" + "=" * 80)
print("ETL VALIDATION COMPLETED")
print("=" * 80)

================================================================================
FINAL ETL DATA QUALITY CHECK
================================================================================

dim_customer
--------------------------------------------------
Rows: 18484
Columns: 15
Duplicate rows: 0
Missing values: 0

dim_employee
--------------------------------------------------
Rows: 21
Columns: 9
Duplicate rows: 0
Missing values: 1

dim_geography
--------------------------------------------------
Rows: 655
Columns: 6
Duplicate rows: 0
Missing values: 0

dim_product
--------------------------------------------------
Rows: 397
Columns: 7
Duplicate rows: 0
Missing values: 0

dim_reseller
--------------------------------------------------
Rows: 701
Columns: 4
Duplicate rows: 0
Missing values: 0

dim_sales_territory
--------------------------------------------------
Rows: 11
Columns: 4
Duplicate rows: 0
Missing values: 0

dim_date
--------------------------------------------------
Rows: 1127
Columns: 9
Duplicate rows: 0
Missing values: 0

fact_internet_sales
--------------------------------------------------
Rows: 60398
Columns: 14
Duplicate rows: 0
Missing values: 60398

fact_reseller_sales
--------------------------------------------------
Rows: 60855
Columns: 15
Duplicate rows: 0
Missing values: 0

fact_sales
--------------------------------------------------
Rows: 121253
Columns: 16
Duplicate rows: 0
Missing values: 242049

================================================================================
ETL VALIDATION COMPLETED
================================================================================

In [ ]:
print("=" * 80)
print("EXPECTED MISSING VALUE VALIDATION")
print("=" * 80)

# 1. DimEmployee - top-level employee
employee_missing = dim_employee_clean["ParentEmployeeKey"].isna().sum()
print(f"\nDimEmployee - ParentEmployeeKey missing: {employee_missing}")
print("Status: Expected - top-level employee has no parent.")

# 2. FactInternetSales - CarrierTrackingNumber
internet_tracking_missing = (
    fact_internet_sales_clean["CarrierTrackingNumber"].isna().sum()
)
print(f"\nFactInternetSales - CarrierTrackingNumber missing: {internet_tracking_missing}")
print("Status: Expected - source field contains no tracking numbers.")

# 3. Combined Fact Sales - channel-specific keys
print("\nFactSales - Channel-specific nulls:")

for channel in ["Internet", "Reseller"]:
    channel_data = fact_sales[fact_sales["SalesChannel"] == channel]

    print(f"\n{channel} Sales:")
    print("Rows:", len(channel_data))
    print("CustomerKey missing:", channel_data["CustomerKey"].isna().sum())
    print("ResellerKey missing:", channel_data["ResellerKey"].isna().sum())
    print("EmployeeKey missing:", channel_data["EmployeeKey"].isna().sum())

print("\n" + "=" * 80)
print("ALL REMAINING NULLS ARE EXPLAINED")
print("=" * 80)

================================================================================
EXPECTED MISSING VALUE VALIDATION
================================================================================

DimEmployee - ParentEmployeeKey missing: 1
Status: Expected - top-level employee has no parent.

FactInternetSales - CarrierTrackingNumber missing: 60398
Status: Expected - source field contains no tracking numbers.

FactSales - Channel-specific nulls:

Internet Sales:
Rows: 60398
CustomerKey missing: 0
ResellerKey missing: 60398
EmployeeKey missing: 60398

Reseller Sales:
Rows: 60855
CustomerKey missing: 60855
ResellerKey missing: 0
EmployeeKey missing: 0

================================================================================
ALL REMAINING NULLS ARE EXPLAINED
================================================================================

In [ ]:
print("=" * 80)
print("CORE BUSINESS KPI BASELINE")
print("=" * 80)

# Total sales
total_sales = fact_sales["SalesAmount"].sum()

# Total cost
total_cost = fact_sales["TotalProductCost"].sum()

# Gross profit
gross_profit = total_sales - total_cost

# Total orders
total_orders = fact_sales["SalesOrderNumber"].nunique()

# Total sales lines
total_sales_lines = len(fact_sales)

# Average Order Value
average_order_value = total_sales / total_orders

# Total discount
total_discount = fact_sales["DiscountAmount"].sum()

# Total freight
total_freight = fact_sales["Freight"].sum()

# Gross profit margin
gross_profit_margin = (gross_profit / total_sales) * 100

print(f"\nTotal Sales: ${total_sales:,.2f}")
print(f"Total Product Cost: ${total_cost:,.2f}")
print(f"Gross Profit: ${gross_profit:,.2f}")
print(f"Gross Profit Margin: {gross_profit_margin:.2f}%")
print(f"Total Orders: {total_orders:,}")
print(f"Total Sales Lines: {total_sales_lines:,}")
print(f"Average Order Value: ${average_order_value:,.2f}")
print(f"Total Discount: ${total_discount:,.2f}")
print(f"Total Freight: ${total_freight:,.2f}")

print("\n" + "=" * 80)
print("SALES BY CHANNEL")
print("=" * 80)

channel_summary = (
    fact_sales
    .groupby("SalesChannel")
    .agg(
        Sales=("SalesAmount", "sum"),
        Orders=("SalesOrderNumber", "nunique"),
        SalesLines=("SalesOrderLineNumber", "count")
    )
    .reset_index()
)

channel_summary["AverageOrderValue"] = (
    channel_summary["Sales"] / channel_summary["Orders"]
)

channel_summary["SalesShare"] = (
    channel_summary["Sales"] / total_sales * 100
)

print(channel_summary)

================================================================================
CORE BUSINESS KPI BASELINE
================================================================================

Total Sales: $109,809,274.20
Total Product Cost: $97,257,907.95
Gross Profit: $12,551,366.25
Gross Profit Margin: 11.43%
Total Orders: 31,455
Total Sales Lines: 121,253
Average Order Value: $3,491.00
Total Discount: $527,507.93
Total Freight: $2,745,235.52

================================================================================
SALES BY CHANNEL
================================================================================
  SalesChannel         Sales  Orders  SalesLines  AverageOrderValue  \
0     Internet  2.935868e+07   27659       60398        1061.451145
1     Reseller  8.045060e+07    3796       60855       21193.518699

   SalesShare
0   26.736063
1   73.263937

In [ ]:
# Merge territory information with the combined sales fact
territory_sales = fact_sales.merge(
    dim_sales_territory_clean[
        [
            "SalesTerritoryKey",
            "SalesTerritoryRegion",
            "SalesTerritoryCountry",
            "SalesTerritoryGroup"
        ]
    ],
    on="SalesTerritoryKey",
    how="left"
)

# Calculate territory-level performance
territory_summary = (
    territory_sales
    .groupby(
        [
            "SalesTerritoryKey",
            "SalesTerritoryRegion",
            "SalesTerritoryCountry",
            "SalesTerritoryGroup"
        ],
        dropna=False
    )
    .agg(
        TotalSales=("SalesAmount", "sum"),
        TotalOrders=("SalesOrderNumber", "nunique"),
        SalesLines=("SalesOrderLineNumber", "count")
    )
    .reset_index()
)

# Calculate Average Order Value
territory_summary["AverageOrderValue"] = (
    territory_summary["TotalSales"]
    / territory_summary["TotalOrders"]
)

# Calculate sales contribution
territory_summary["SalesShare"] = (
    territory_summary["TotalSales"]
    / total_sales
    * 100
)

# Sort by total sales
territory_summary = territory_summary.sort_values(
    "TotalSales",
    ascending=False
).reset_index(drop=True)

print("=" * 80)
print("SALES TERRITORY PERFORMANCE")
print("=" * 80)

print(territory_summary.to_string(index=False))

print("\n" + "=" * 80)
print("LOWEST SALES TERRITORIES")
print("=" * 80)

print(
    territory_summary[
        [
            "SalesTerritoryRegion",
            "TotalSales",
            "TotalOrders",
            "AverageOrderValue",
            "SalesShare"
        ]
    ]
    .sort_values("TotalSales")
    .head(5)
    .to_string(index=False)
)

================================================================================
SALES TERRITORY PERFORMANCE
================================================================================
 SalesTerritoryKey SalesTerritoryRegion SalesTerritoryCountry SalesTerritoryGroup   TotalSales  TotalOrders  SalesLines  AverageOrderValue  SalesShare
                 4            Southwest         United States       North America 2.418461e+07         6224       25644        3885.702057   22.024196
                 6               Canada                Canada       North America 1.635577e+07         4067       19064        4021.581131   14.894708
                 1            Northwest         United States       North America 1.608494e+07         4594       16865        3501.293546   14.648073
                 9            Australia             Australia             Pacific 1.065534e+07         6843       15058        1557.114710    9.703494
                 3              Central         United States       North America 7.909009e+06          385        5832       20542.880538    7.202496
                 5            Southeast         United States       North America 7.879655e+06          486        5976       16213.282047    7.175765
                10       United Kingdom        United Kingdom              Europe 7.670721e+06         3219       10426        2382.951549    6.985495
                 7               France                France              Europe 7.251556e+06         2672        9088        2713.905557    6.603773
                 2            Northeast         United States       North America 6.939374e+06          352        5836       19714.132054    6.319479
                 8              Germany               Germany              Europe 4.878300e+06         2613        7464        1866.934702    4.442521

================================================================================
LOWEST SALES TERRITORIES
================================================================================
SalesTerritoryRegion   TotalSales  TotalOrders  AverageOrderValue  SalesShare
             Germany 4878300.3755         2613        1866.934702    4.442521
           Northeast 6939374.4830          352       19714.132054    6.319479
              France 7251555.6493         2672        2713.905557    6.603773
      United Kingdom 7670721.0375         3219        2382.951549    6.985495
           Southeast 7879655.0747          486       16213.282047    7.175765

In [ ]:
# Calculate median benchmarks
sales_median = territory_summary["TotalSales"].median()
aov_median = territory_summary["AverageOrderValue"].median()

# Classify territory performance
def classify_territory(row):
    if (
        row["TotalSales"] < sales_median
        and row["AverageOrderValue"] < aov_median
    ):
        return "Underperforming"
    elif (
        row["TotalSales"] >= sales_median
        and row["AverageOrderValue"] >= aov_median
    ):
        return "High Performing"
    elif row["TotalSales"] >= sales_median:
        return "High Sales / Low AOV"
    else:
        return "Low Sales / High AOV"

territory_summary["PerformanceCategory"] = territory_summary.apply(
    classify_territory,
    axis=1
)

print("=" * 80)
print("TERRITORY PERFORMANCE BENCHMARKS")
print("=" * 80)

print(f"\nMedian Total Sales: ${sales_median:,.2f}")
print(f"Median Average Order Value: ${aov_median:,.2f}")

print("\n" + "=" * 80)
print("TERRITORY CLASSIFICATION")
print("=" * 80)

print(
    territory_summary[
        [
            "SalesTerritoryRegion",
            "TotalSales",
            "AverageOrderValue",
            "SalesShare",
            "PerformanceCategory"
        ]
    ].to_string(index=False)
)

print("\n" + "=" * 80)
print("UNDERPERFORMING TERRITORIES")
print("=" * 80)

underperforming = territory_summary[
    territory_summary["PerformanceCategory"] == "Underperforming"
]

print(
    underperforming[
        [
            "SalesTerritoryRegion",
            "TotalSales",
            "AverageOrderValue",
            "SalesShare",
            "PerformanceCategory"
        ]
    ].sort_values("TotalSales")
    .to_string(index=False)
)

================================================================================
TERRITORY PERFORMANCE BENCHMARKS
================================================================================

Median Total Sales: $7,894,332.04
Median Average Order Value: $3,693.50

================================================================================
TERRITORY CLASSIFICATION
================================================================================
SalesTerritoryRegion   TotalSales  AverageOrderValue  SalesShare  PerformanceCategory
           Southwest 2.418461e+07        3885.702057   22.024196      High Performing
              Canada 1.635577e+07        4021.581131   14.894708      High Performing
           Northwest 1.608494e+07        3501.293546   14.648073 High Sales / Low AOV
           Australia 1.065534e+07        1557.114710    9.703494 High Sales / Low AOV
             Central 7.909009e+06       20542.880538    7.202496      High Performing
           Southeast 7.879655e+06       16213.282047    7.175765 Low Sales / High AOV
      United Kingdom 7.670721e+06        2382.951549    6.985495      Underperforming
              France 7.251556e+06        2713.905557    6.603773      Underperforming
           Northeast 6.939374e+06       19714.132054    6.319479 Low Sales / High AOV
             Germany 4.878300e+06        1866.934702    4.442521      Underperforming

================================================================================
UNDERPERFORMING TERRITORIES
================================================================================
SalesTerritoryRegion   TotalSales  AverageOrderValue  SalesShare PerformanceCategory
             Germany 4878300.3755        1866.934702    4.442521     Underperforming
              France 7251555.6493        2713.905557    6.603773     Underperforming
      United Kingdom 7670721.0375        2382.951549    6.985495     Underperforming

In [ ]:
# Connect Internet Sales with Customer information
customer_sales = fact_internet_sales_clean.merge(
    dim_customer_clean[
        [
            "CustomerKey",
            "CustomerName",
            "Occupation",
            "YearlyIncome",
            "Age",
            "AgeGroup"
        ]
    ],
    on="CustomerKey",
    how="left"
)

# Calculate customer-level sales
customer_summary = (
    customer_sales
    .groupby(
        [
            "CustomerKey",
            "CustomerName",
            "Occupation",
            "YearlyIncome",
            "Age",
            "AgeGroup"
        ],
        dropna=False
    )
    .agg(
        TotalSales=("SalesAmount", "sum"),
        TotalOrders=("SalesOrderNumber", "nunique")
    )
    .reset_index()
)

# Average Sales per Customer by Occupation
occupation_summary = (
    customer_summary
    .groupby("Occupation", dropna=False)
    .agg(
        Customers=("CustomerKey", "nunique"),
        TotalSales=("TotalSales", "sum"),
        AverageSalesPerCustomer=("TotalSales", "mean"),
        AverageIncome=("YearlyIncome", "mean")
    )
    .reset_index()
    .sort_values("AverageSalesPerCustomer", ascending=False)
)

print("=" * 80)
print("CUSTOMER SEGMENTATION BY OCCUPATION")
print("=" * 80)

print(
    occupation_summary.to_string(index=False)
)

print("\n" + "=" * 80)
print("TOP OCCUPATION SEGMENTS")
print("=" * 80)

print(
    occupation_summary.head(5).to_string(index=False)
)

================================================================================
CUSTOMER SEGMENTATION BY OCCUPATION
================================================================================
    Occupation  Customers   TotalSales  AverageSalesPerCustomer  AverageIncome
  Professional       5520 9907977.2811              1794.923420   74184.782609
    Management       3075 5467861.5445              1778.166356   92325.203252
      Clerical       2928 4684786.6430              1599.995438   30710.382514
Skilled Manual       4577 6440080.8589              1407.052842   51715.097225
        Manual       2384 2857970.8932              1198.813294   16451.342282

================================================================================
TOP OCCUPATION SEGMENTS
================================================================================
    Occupation  Customers   TotalSales  AverageSalesPerCustomer  AverageIncome
  Professional       5520 9907977.2811              1794.923420   74184.782609
    Management       3075 5467861.5445              1778.166356   92325.203252
      Clerical       2928 4684786.6430              1599.995438   30710.382514
Skilled Manual       4577 6440080.8589              1407.052842   51715.097225
        Manual       2384 2857970.8932              1198.813294   16451.342282

In [ ]:
# Create annual income bands
def assign_income_group(income):
    if income < 30000:
        return "<30K"
    elif income < 50000:
        return "30K-50K"
    elif income < 75000:
        return "50K-75K"
    elif income < 100000:
        return "75K-100K"
    else:
        return "100K+"

customer_summary["IncomeGroup"] = customer_summary["YearlyIncome"].apply(
    assign_income_group
)

# Aggregate sales by income group
income_summary = (
    customer_summary
    .groupby("IncomeGroup", dropna=False)
    .agg(
        Customers=("CustomerKey", "nunique"),
        TotalSales=("TotalSales", "sum"),
        AverageSalesPerCustomer=("TotalSales", "mean"),
        AverageIncome=("YearlyIncome", "mean")
    )
    .reset_index()
)

# Keep income groups in logical order
income_order = [
    "<30K",
    "30K-50K",
    "50K-75K",
    "75K-100K",
    "100K+"
]

income_summary["IncomeGroup"] = pd.Categorical(
    income_summary["IncomeGroup"],
    categories=income_order,
    ordered=True
)

income_summary = income_summary.sort_values("IncomeGroup")

print("=" * 80)
print("CUSTOMER SEGMENTATION BY ANNUAL INCOME")
print("=" * 80)

print(
    income_summary.to_string(index=False)
)

print("\n" + "=" * 80)
print("HIGHEST VALUE INCOME SEGMENTS")
print("=" * 80)

print(
    income_summary
    .sort_values("AverageSalesPerCustomer", ascending=False)
    .head(3)
    .to_string(index=False)
)

================================================================================
CUSTOMER SEGMENTATION BY ANNUAL INCOME
================================================================================
IncomeGroup  Customers   TotalSales  AverageSalesPerCustomer  AverageIncome
       <30K       2922 3407009.5807              1165.985483   16047.227926
    30K-50K       5034 7148868.5359              1420.116912   35456.893127
    50K-75K       6146 9520310.3688              1549.025442   62731.858119
   75K-100K       2184 4458519.4690              2041.446643   83855.311355
      100K+       2198 4823969.2663              2194.708492  120641.492266

================================================================================
HIGHEST VALUE INCOME SEGMENTS
================================================================================
IncomeGroup  Customers   TotalSales  AverageSalesPerCustomer  AverageIncome
      100K+       2198 4823969.2663              2194.708492  120641.492266
   75K-100K       2184 4458519.4690              2041.446643   83855.311355
    50K-75K       6146 9520310.3688              1549.025442   62731.858119

In [ ]:
# Customer sales by age group
age_summary = (
    customer_summary
    .groupby("AgeGroup", dropna=False)
    .agg(
        Customers=("CustomerKey", "nunique"),
        TotalSales=("TotalSales", "sum"),
        AverageSalesPerCustomer=("TotalSales", "mean"),
        AverageIncome=("YearlyIncome", "mean")
    )
    .reset_index()
)

# Keep age groups in logical order
age_order = [
    "<25",
    "25-30",
    "30-35",
    "35-40",
    "40-45",
    "45-50",
    "50+"
]

age_summary["AgeGroup"] = pd.Categorical(
    age_summary["AgeGroup"],
    categories=age_order,
    ordered=True
)

age_summary = age_summary.sort_values("AgeGroup")

# Calculate percentage of customers under 50
under_50 = customer_summary[customer_summary["Age"] < 50]

under_50_customers = under_50["CustomerKey"].nunique()
total_customers = customer_summary["CustomerKey"].nunique()
under_50_customer_share = (under_50_customers / total_customers) * 100

print("=" * 80)
print("CUSTOMER ANALYSIS BY AGE GROUP")
print("=" * 80)

print(
    age_summary.to_string(index=False)
)

print("\n" + "=" * 80)
print("UNDER-50 CUSTOMER ANALYSIS")
print("=" * 80)

print(f"Customers Under 50: {under_50_customers:,}")
print(f"Total Customers: {total_customers:,}")
print(f"Under-50 Customer Share: {under_50_customer_share:.2f}%")

print("\n" + "=" * 80)
print("UNDER-50 AGE GROUPS BY AVERAGE SALES PER CUSTOMER")
print("=" * 80)

print(
    age_summary[
        age_summary["AgeGroup"].isin(
            ["25-30", "30-35", "35-40", "40-45", "45-50"]
        )
    ]
    .sort_values("AverageSalesPerCustomer", ascending=False)
    .to_string(index=False)
)

================================================================================
CUSTOMER ANALYSIS BY AGE GROUP
================================================================================
AgeGroup  Customers   TotalSales  AverageSalesPerCustomer  AverageIncome
   25-30       1129 1681757.8518              1489.599514   37307.351639
   30-35       3199 4718560.9392              1475.011235   48171.303532
   35-40       3255 6248645.6429              1919.706803   58273.425499
   40-45       3006 4883548.9065              1624.600435   60864.936793
   45-50       2282 3892734.3096              1705.843256   61822.962314
     50+       5613 7933429.5707              1413.402738   62230.536255

================================================================================
UNDER-50 CUSTOMER ANALYSIS
================================================================================
Customers Under 50: 12,871
Total Customers: 18,484
Under-50 Customer Share: 69.63%

================================================================================
UNDER-50 AGE GROUPS BY AVERAGE SALES PER CUSTOMER
================================================================================
AgeGroup  Customers   TotalSales  AverageSalesPerCustomer  AverageIncome
   35-40       3255 6248645.6429              1919.706803   58273.425499
   45-50       2282 3892734.3096              1705.843256   61822.962314
   40-45       3006 4883548.9065              1624.600435   60864.936793
   25-30       1129 1681757.8518              1489.599514   37307.351639
   30-35       3199 4718560.9392              1475.011235   48171.303532

In [ ]:
# Detailed customer segmentation
customer_segment_analysis = (
    customer_summary
    .groupby(
        ["Occupation", "IncomeGroup", "AgeGroup"],
        dropna=False
    )
    .agg(
        Customers=("CustomerKey", "nunique"),
        TotalSales=("TotalSales", "sum"),
        AverageSalesPerCustomer=("TotalSales", "mean"),
        AverageIncome=("YearlyIncome", "mean")
    )
    .reset_index()
)

# Focus on customers under 50
under_50_segments = customer_segment_analysis[
    customer_segment_analysis["AgeGroup"].isin(
        ["25-30", "30-35", "35-40", "40-45", "45-50"]
    )
].copy()

under_50_segments = under_50_segments.sort_values(
    "AverageSalesPerCustomer",
    ascending=False
).reset_index(drop=True)

print("=" * 80)
print("UNDER-50 CUSTOMER SEGMENTATION")
print("=" * 80)

print(
    under_50_segments.head(15).to_string(index=False)
)

print("\n" + "=" * 80)
print("TOP 10 UNDER-50 CUSTOMER SEGMENTS")
print("=" * 80)

print(
    under_50_segments[
        [
            "Occupation",
            "IncomeGroup",
            "AgeGroup",
            "Customers",
            "TotalSales",
            "AverageSalesPerCustomer"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

================================================================================
UNDER-50 CUSTOMER SEGMENTATION
================================================================================
    Occupation IncomeGroup AgeGroup  Customers  TotalSales  AverageSalesPerCustomer  AverageIncome
    Management     30K-50K    40-45          1   5249.9182              5249.918200        40000.0
    Management       100K+    25-30         24  90055.9656              3752.331900       107500.0
  Professional       100K+    35-40        100 345100.2298              3451.002298       115600.0
  Professional       100K+    30-35         40 128021.3580              3200.533950       114750.0
    Management     30K-50K    45-50          5  15369.5225              3073.904500        40000.0
    Management    75K-100K    30-35         53 162010.4433              3056.800817   84339.622642
  Professional    75K-100K    25-30         40 115511.0369              2887.775922        85500.0
    Management     50K-75K    40-45          9  25947.5600              2883.062222   68888.888889
      Clerical        <30K    25-30         75 209594.2321              2794.589761        20000.0
      Clerical        <30K    30-35         38 104724.9927              2755.920861   19736.842105
    Management       100K+    30-35        153 408195.8412              2667.946675   113856.20915
    Management       100K+    35-40        296 768350.1361              2595.777487  115439.189189
Skilled Manual    75K-100K    45-50         72 182707.8635              2537.609215        80000.0
  Professional    75K-100K    30-35        196 492026.3437              2510.338488   84183.673469
    Management    75K-100K    25-30         14  34243.2196              2445.944257   83571.428571

================================================================================
TOP 10 UNDER-50 CUSTOMER SEGMENTS
================================================================================
  Occupation IncomeGroup AgeGroup  Customers  TotalSales  AverageSalesPerCustomer
  Management     30K-50K    40-45          1   5249.9182              5249.918200
  Management       100K+    25-30         24  90055.9656              3752.331900
Professional       100K+    35-40        100 345100.2298              3451.002298
Professional       100K+    30-35         40 128021.3580              3200.533950
  Management     30K-50K    45-50          5  15369.5225              3073.904500
  Management    75K-100K    30-35         53 162010.4433              3056.800817
Professional    75K-100K    25-30         40 115511.0369              2887.775922
  Management     50K-75K    40-45          9  25947.5600              2883.062222
    Clerical        <30K    25-30         75 209594.2321              2794.589761
    Clerical        <30K    30-35         38 104724.9927              2755.920861

In [ ]:
# Filter out very small segments for reliable marketing analysis
reliable_under_50_segments = under_50_segments[
    under_50_segments["Customers"] >= 50
].copy()

# Rank reliable segments by average sales per customer
reliable_under_50_segments["SegmentRank"] = (
    reliable_under_50_segments["AverageSalesPerCustomer"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

reliable_under_50_segments = reliable_under_50_segments.sort_values(
    ["AverageSalesPerCustomer", "Customers"],
    ascending=[False, False]
).reset_index(drop=True)

print("=" * 80)
print("RELIABLE UNDER-50 MARKETING SEGMENTS")
print("=" * 80)

print(
    reliable_under_50_segments[
        [
            "SegmentRank",
            "Occupation",
            "IncomeGroup",
            "AgeGroup",
            "Customers",
            "TotalSales",
            "AverageSalesPerCustomer",
            "AverageIncome"
        ]
    ]
    .head(15)
    .to_string(index=False)
)

print("\n" + "=" * 80)
print("TOP 5 RELIABLE MARKETING SEGMENTS")
print("=" * 80)

print(
    reliable_under_50_segments[
        [
            "Occupation",
            "IncomeGroup",
            "AgeGroup",
            "Customers",
            "TotalSales",
            "AverageSalesPerCustomer"
        ]
    ]
    .head(5)
    .to_string(index=False)
)

================================================================================
RELIABLE UNDER-50 MARKETING SEGMENTS
================================================================================
 SegmentRank     Occupation IncomeGroup AgeGroup  Customers   TotalSales  AverageSalesPerCustomer  AverageIncome
           1   Professional       100K+    35-40        100  345100.2298              3451.002298       115600.0
           2     Management    75K-100K    30-35         53  162010.4433              3056.800817   84339.622642
           3       Clerical        <30K    25-30         75  209594.2321              2794.589761        20000.0
           4     Management       100K+    30-35        153  408195.8412              2667.946675   113856.20915
           5     Management       100K+    35-40        296  768350.1361              2595.777487  115439.189189
           6 Skilled Manual    75K-100K    45-50         72  182707.8635              2537.609215        80000.0
           7   Professional    75K-100K    30-35        196  492026.3437              2510.338488   84183.673469
           8     Management    75K-100K    35-40        139  329751.3005              2372.311514   82230.215827
           9   Professional    75K-100K    35-40        237  560010.5201              2362.913587   85147.679325
          10       Clerical     30K-50K    35-40        427 1000942.9058              2344.128585   35597.189696
          11   Professional       100K+    45-50        190  416798.4341              2193.675969  116526.315789
          12     Management       100K+    45-50        153  299384.3794              1956.760650  124836.601307
          13   Professional     50K-75K    35-40        624 1217562.6250              1951.222155   64983.974359
          14     Management       100K+    40-45        294  552277.1703              1878.493777   121938.77551
          15       Clerical     30K-50K    40-45        343  633916.1480              1848.152035   33090.379009

================================================================================
TOP 5 RELIABLE MARKETING SEGMENTS
================================================================================
  Occupation IncomeGroup AgeGroup  Customers  TotalSales  AverageSalesPerCustomer
Professional       100K+    35-40        100 345100.2298              3451.002298
  Management    75K-100K    30-35         53 162010.4433              3056.800817
    Clerical        <30K    25-30         75 209594.2321              2794.589761
  Management       100K+    30-35        153 408195.8412              2667.946675
  Management       100K+    35-40        296 768350.1361              2595.777487

In [ ]:
# Final customer analytics table for Power BI
customer_analytics = customer_summary[
    [
        "CustomerKey",
        "CustomerName",
        "Occupation",
        "YearlyIncome",
        "IncomeGroup",
        "Age",
        "AgeGroup",
        "TotalSales",
        "TotalOrders"
    ]
].copy()

# Add average order value at customer level
customer_analytics["CustomerAOV"] = (
    customer_analytics["TotalSales"]
    / customer_analytics["TotalOrders"]
)

# Add under-50 marketing flag
customer_analytics["Under50Flag"] = np.where(
    customer_analytics["Age"] < 50,
    "Under 50",
    "50+"
)

print("=" * 80)
print("FINAL CUSTOMER ANALYTICS TABLE")
print("=" * 80)

print(f"Rows: {len(customer_analytics):,}")
print(f"Columns: {len(customer_analytics.columns)}")

print("\nColumns:")
print(customer_analytics.columns.tolist())

print("\nMissing Values:")
print(customer_analytics.isna().sum())

print("\nSample Records:")
print(customer_analytics.head(10).to_string(index=False))

================================================================================
FINAL CUSTOMER ANALYTICS TABLE
================================================================================
Rows: 18,484
Columns: 11

Columns:
['CustomerKey', 'CustomerName', 'Occupation', 'YearlyIncome', 'IncomeGroup', 'Age', 'AgeGroup', 'TotalSales', 'TotalOrders', 'CustomerAOV', 'Under50Flag']

Missing Values:
CustomerKey     0
CustomerName    0
Occupation      0
YearlyIncome    0
IncomeGroup     0
Age             0
AgeGroup        0
TotalSales      0
TotalOrders     0
CustomerAOV     0
Under50Flag     0
dtype: int64

Sample Records:
 CustomerKey      CustomerName   Occupation  YearlyIncome IncomeGroup  Age AgeGroup  TotalSales  TotalOrders  CustomerAOV Under50Flag
       11000          Jon Yang Professional         90000    75K-100K   42    40-45     8248.99            3  2749.663333    Under 50
       11001      Eugene Huang Professional         60000     50K-75K   37    35-40     6383.88            3  2127.960000    Under 50
       11002      Ruben Torres Professional         60000     50K-75K   42    40-45     8114.04            3  2704.680000    Under 50
       11003       Christy Zhu Professional         70000     50K-75K   40    40-45     8139.29            3  2713.096667    Under 50
       11004 Elizabeth Johnson Professional         80000    75K-100K   34    30-35     8196.01            3  2732.003333    Under 50
       11005        Julio Ruiz Professional         70000     50K-75K   37    35-40     8121.33            3  2707.110000    Under 50
       11006     Janet Alvarez Professional         70000     50K-75K   37    35-40     8119.03            3  2706.343333    Under 50
       11007       Marco Mehta Professional         60000     50K-75K   44    40-45     8211.00            3  2737.000000    Under 50
       11008       Rob Verhoff Professional         60000     50K-75K   38    35-40     8106.31            3  2702.103333    Under 50
       11009   Shannon Carlson Professional         70000     50K-75K   44    40-45     8091.33            3  2697.110000    Under 50

In [ ]:
# Merge product information with combined sales
product_sales = fact_sales.merge(
    dim_product_clean[
        [
            "ProductKey",
            "Product",
            "Color",
            "Model",
            "Subcategory",
            "Category"
        ]
    ],
    on="ProductKey",
    how="left"
)

# Product-level performance
product_summary = (
    product_sales
    .groupby(
        [
            "ProductKey",
            "Product",
            "Color",
            "Model",
            "Subcategory",
            "Category"
        ],
        dropna=False
    )
    .agg(
        TotalSales=("SalesAmount", "sum"),
        TotalCost=("TotalProductCost", "sum"),
        TotalQuantity=("SalesOrderLineNumber", "count"),
        TotalOrders=("SalesOrderNumber", "nunique"),
        TotalDiscount=("DiscountAmount", "sum")
    )
    .reset_index()
)

# Derived metrics
product_summary["GrossProfit"] = (
    product_summary["TotalSales"]
    - product_summary["TotalCost"]
)

product_summary["ProfitMargin"] = (
    product_summary["GrossProfit"]
    / product_summary["TotalSales"]
    * 100
)

product_summary["AverageOrderValue"] = (
    product_summary["TotalSales"]
    / product_summary["TotalOrders"]
)

product_summary["SalesShare"] = (
    product_summary["TotalSales"]
    / total_sales
    * 100
)

product_summary = product_summary.sort_values(
    "TotalSales",
    ascending=False
).reset_index(drop=True)

print("=" * 80)
print("PRODUCT PERFORMANCE ANALYSIS")
print("=" * 80)

print(f"Total Products: {len(product_summary):,}")

print("\n" + "=" * 80)
print("TOP 10 PRODUCTS BY SALES")
print("=" * 80)

print(
    product_summary[
        [
            "Product",
            "Category",
            "Subcategory",
            "TotalSales",
            "TotalOrders",
            "GrossProfit",
            "ProfitMargin"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

print("\n" + "=" * 80)
print("BOTTOM 10 PRODUCTS BY SALES")
print("=" * 80)

print(
    product_summary[
        [
            "Product",
            "Category",
            "Subcategory",
            "TotalSales",
            "TotalOrders",
            "GrossProfit",
            "ProfitMargin"
        ]
    ]
    .sort_values("TotalSales")
    .head(10)
    .to_string(index=False)
)

================================================================================
PRODUCT PERFORMANCE ANALYSIS
================================================================================
Total Products: 350

================================================================================
TOP 10 PRODUCTS BY SALES
================================================================================
                Product Category    Subcategory   TotalSales  TotalOrders  GrossProfit  ProfitMargin
 Mountain-200 Black, 38    Bikes Mountain Bikes 2589363.7774          743  569917.9405     22.009960
 Mountain-200 Black, 42    Bikes Mountain Bikes 2265485.3791          671  554026.9420     24.455110
Mountain-200 Silver, 38    Bikes Mountain Bikes 2160981.5974          641  547316.7349     25.327228
 Mountain-200 Black, 46    Bikes Mountain Bikes 1957528.2445          633  525261.6373     26.832902
Mountain-200 Silver, 42    Bikes Mountain Bikes 1914547.8517          599  499585.2507     26.094164
Mountain-200 Silver, 46    Bikes Mountain Bikes 1906248.5514          599  509004.6234     26.701902
       Road-150 Red, 56    Bikes     Road Bikes 1847818.6280          475  406079.2792     21.976144
 Mountain-200 Black, 38    Bikes Mountain Bikes 1811229.0230          509  302904.1830     16.723682
  Road-350-W Yellow, 48    Bikes     Road Bikes 1774883.5572          566   19052.3372      1.073442
       Road-150 Red, 62    Bikes     Road Bikes 1769096.6880          470  466320.1680     26.359225

================================================================================
BOTTOM 10 PRODUCTS BY SALES
================================================================================
                         Product   Category     Subcategory  TotalSales  TotalOrders  GrossProfit  ProfitMargin
             LL Road Seat/Saddle Components         Saddles    162.7200            6      42.3070     25.999877
       LL Road Frame - Black, 60 Components     Road Frames    178.5808            1       2.3811      1.333346
          Mountain Bike Socks, L   Clothing           Socks    513.0000           44     207.3330     40.415789
     LL Touring Frame - Blue, 58 Components  Touring Frames    800.2080            2       0.8004      0.100024
   LL Mountain Frame - Black, 40 Components Mountain Frames   1198.9920            6     104.7120      8.733336
         LL Road Frame - Red, 52 Components     Road Frames   1287.5674            6      17.1675      1.333328
          LL Touring Seat/Saddle Components         Saddles   1480.7520           43     384.9937     25.999877
ML Mountain Frame-W - Silver, 38 Components Mountain Frames   1529.1780            5     133.5481      8.733326
           LL Touring Handlebars Components      Handlebars   1548.6240           30     402.6400     25.999855
                      LL Headset Components        Headsets   1949.4000           46     506.8440     26.000000

In [ ]:
# Category-level performance
category_summary = (
    product_summary
    .groupby("Category", dropna=False)
    .agg(
        Products=("ProductKey", "nunique"),
        TotalSales=("TotalSales", "sum"),
        TotalCost=("TotalCost", "sum"),
        TotalOrders=("TotalOrders", "sum"),
        GrossProfit=("GrossProfit", "sum")
    )
    .reset_index()
)

# Derived metrics
category_summary["ProfitMargin"] = (
    category_summary["GrossProfit"]
    / category_summary["TotalSales"]
    * 100
)

category_summary["AverageSalesPerProduct"] = (
    category_summary["TotalSales"]
    / category_summary["Products"]
)

category_summary["SalesShare"] = (
    category_summary["TotalSales"]
    / total_sales
    * 100
)

category_summary = category_summary.sort_values(
    "TotalSales",
    ascending=False
).reset_index(drop=True)

print("=" * 80)
print("PRODUCT CATEGORY PERFORMANCE")
print("=" * 80)

print(
    category_summary.to_string(index=False)
)

print("\n" + "=" * 80)
print("CATEGORY SUMMARY")
print("=" * 80)

print(
    category_summary[
        [
            "Category",
            "Products",
            "TotalSales",
            "GrossProfit",
            "ProfitMargin",
            "AverageSalesPerProduct",
            "SalesShare"
        ]
    ].to_string(index=False)
)

================================================================================
PRODUCT CATEGORY PERFORMANCE
================================================================================
   Category  Products   TotalSales    TotalCost  TotalOrders  GrossProfit  ProfitMargin  AverageSalesPerProduct  SalesShare
      Bikes       125 9.462053e+07 8.410543e+07        40005 1.051510e+07     11.112913           756964.209662   86.168064
 Components       150 1.179908e+07 1.076611e+07        18687 1.032966e+06      8.754638            78660.511056   10.745064
   Clothing        45 2.117613e+06 1.748777e+06        21368 3.688360e+05     17.417532            47058.076647    1.928447
Accessories        30 1.272058e+06 6.375907e+05        41193 6.344672e+05     49.877224            42401.929593    1.158425

================================================================================
CATEGORY SUMMARY
================================================================================
   Category  Products   TotalSales  GrossProfit  ProfitMargin  AverageSalesPerProduct  SalesShare
      Bikes       125 9.462053e+07 1.051510e+07     11.112913           756964.209662   86.168064
 Components       150 1.179908e+07 1.032966e+06      8.754638            78660.511056   10.745064
   Clothing        45 2.117613e+06 3.688360e+05     17.417532            47058.076647    1.928447
Accessories        30 1.272058e+06 6.344672e+05     49.877224            42401.929593    1.158425

In [ ]:
# Create time-based sales analysis
time_sales = fact_sales.copy()

time_sales["Year"] = time_sales["OrderDate"].dt.year
time_sales["MonthNumber"] = time_sales["OrderDate"].dt.month
time_sales["MonthName"] = time_sales["OrderDate"].dt.month_name()
time_sales["YearMonth"] = time_sales["OrderDate"].dt.strftime("%Y-%m")

# Yearly sales summary
yearly_sales = (
    time_sales
    .groupby("Year")
    .agg(
        TotalSales=("SalesAmount", "sum"),
        TotalOrders=("SalesOrderNumber", "nunique"),
        GrossProfit=("SalesAmount", lambda x: x.sum())
    )
    .reset_index()
)

# Calculate yearly cost separately
yearly_cost = (
    time_sales
    .groupby("Year")["TotalProductCost"]
    .sum()
    .reset_index(name="TotalCost")
)

yearly_sales = yearly_sales.merge(
    yearly_cost,
    on="Year",
    how="left"
)

yearly_sales["GrossProfit"] = (
    yearly_sales["TotalSales"]
    - yearly_sales["TotalCost"]
)

yearly_sales["ProfitMargin"] = (
    yearly_sales["GrossProfit"]
    / yearly_sales["TotalSales"]
    * 100
)

yearly_sales["AverageOrderValue"] = (
    yearly_sales["TotalSales"]
    / yearly_sales["TotalOrders"]
)

print("=" * 80)
print("YEARLY SALES PERFORMANCE")
print("=" * 80)

print(
    yearly_sales.to_string(index=False)
)

# Monthly sales summary
monthly_sales = (
    time_sales
    .groupby(
        ["Year", "MonthNumber", "MonthName"],
        as_index=False
    )
    .agg(
        TotalSales=("SalesAmount", "sum"),
        TotalOrders=("SalesOrderNumber", "nunique")
    )
)

monthly_sales["AverageOrderValue"] = (
    monthly_sales["TotalSales"]
    / monthly_sales["TotalOrders"]
)

monthly_sales = monthly_sales.sort_values(
    ["Year", "MonthNumber"]
).reset_index(drop=True)

print("\n" + "=" * 80)
print("MONTHLY SALES PERFORMANCE")
print("=" * 80)

print(
    monthly_sales.to_string(index=False)
)

================================================================================
YEARLY SALES PERFORMANCE
================================================================================
 Year   TotalSales  TotalOrders  GrossProfit    TotalCost  ProfitMargin  AverageOrderValue
 2010 5.327496e+05           52   34882.4084 4.978672e+05      6.547618       10245.184906
 2011 2.526833e+07         2989 2873483.8756 2.239484e+07     11.371879        8453.773384
 2012 3.403612e+07         4546 3343906.0623 3.069221e+07      9.824582        7487.047234
 2013 4.992638e+07        22997 6273540.9644 4.365284e+07     12.565582        2170.995543
 2014 4.569472e+04          871   25552.9376 2.014178e+04     55.920985          52.462365

================================================================================
MONTHLY SALES PERFORMANCE
================================================================================
 Year  MonthNumber MonthName   TotalSales  TotalOrders  AverageOrderValue
 2010           12  December  532749.6151           52       10245.184906
 2011            1   January 2008232.2270          219        9170.010169
 2011            2  February  466334.9030          144        3238.436826
 2011            3     March 2495816.7335          250        9983.266934
 2011            4     April  502073.8458          157        3197.922585
 2011            5       May 4588761.8161          327       14032.910753
 2011            6      June  737839.8214          230        3207.999223
 2011            7      July 1309863.2511          228        5745.014259
 2011            8    August 3970627.2790          336       11817.343092
 2011            9 September 1485983.4400          222        6693.619099
 2011           10   October 2977324.7150          306        9729.819330
 2011           11  November 1662349.5829          276        6023.005735
 2011           12  December 3063121.0286          294       10418.779009
 2012            1   January 4096554.8398          391       10477.122352
 2012            2  February 3392353.3868          371        9143.809668
 2012            3     March 2175637.2180          285        7633.814800
 2012            4     April 3454151.9405          352        9812.931649
 2012            5       May 2544091.1055          321        7925.517463
 2012            6      June 1872701.9762          383        4889.561296
 2012            7      July 2829404.8189          378        7485.197934
 2012            8    August 2087872.4623          400        5219.681156
 2012            9 September 2351455.8846          343        6855.556515
 2012           10   October 3415912.1651          447        7641.861667
 2012           11  November 2525828.2235          426        5929.174234
 2012           12  December 3290152.7061          449        7327.734312
 2013            1   January 5070661.4199          817        6206.439926
 2013            2  February 4818922.7779         1597        3017.484520
 2013            3     March 3332023.2665         1789        1862.506018
 2013            4     April 4529184.1733         1790        2530.270488
 2013            5       May 4795541.6618         1968        2436.758974
 2013            6      June 3305725.1042         2101        1573.405571
 2013            7      July 4070976.6033         2049        1986.811422
 2013            8    August 4289719.1775         2140        2004.541672
 2013            9 September 3654220.9143         1977        1848.366674
 2013           10   October 4987894.1945         2310        2159.261556
 2013           11  November 5197154.9140         2267        2292.525326
 2013           12  December 1874360.2900         2192         855.091373
 2014            1   January   45694.7200          871          52.462365

In [ ]:
# Year-over-year sales growth
yearly_growth = yearly_sales.copy()

yearly_growth["YoYGrowth"] = (
    yearly_growth["TotalSales"].pct_change() * 100
)

# Exclude partial years from growth comparison
# 2010 and 2014 are partial years in this dataset
complete_years = yearly_growth[
    yearly_growth["Year"].isin([2011, 2012, 2013])
].copy()

print("=" * 80)
print("YEAR-OVER-YEAR SALES GROWTH")
print("=" * 80)

print(
    complete_years[
        [
            "Year",
            "TotalSales",
            "TotalOrders",
            "AverageOrderValue",
            "GrossProfit",
            "ProfitMargin",
            "YoYGrowth"
        ]
    ].to_string(index=False)
)

print("\n" + "=" * 80)
print("STRONGEST COMPLETE YEAR")
print("=" * 80)

best_year = complete_years.loc[
    complete_years["TotalSales"].idxmax()
]

print(f"Year: {int(best_year['Year'])}")
print(f"Total Sales: ${best_year['TotalSales']:,.2f}")
print(f"Total Orders: {int(best_year['TotalOrders']):,}")
print(f"Average Order Value: ${best_year['AverageOrderValue']:,.2f}")
print(f"Profit Margin: {best_year['ProfitMargin']:.2f}%")

print("\n" + "=" * 80)
print("HIGHEST YEAR-OVER-YEAR GROWTH")
print("=" * 80)

growth_year = complete_years.loc[
    complete_years["YoYGrowth"].idxmax()
]

print(f"Year: {int(growth_year['Year'])}")
print(f"YoY Sales Growth: {growth_year['YoYGrowth']:.2f}%")

================================================================================
YEAR-OVER-YEAR SALES GROWTH
================================================================================
 Year   TotalSales  TotalOrders  AverageOrderValue  GrossProfit  ProfitMargin   YoYGrowth
 2011 2.526833e+07         2989        8453.773384 2873483.8756     11.371879 4643.002703
 2012 3.403612e+07         4546        7487.047234 3343906.0623      9.824582   34.698726
 2013 4.992638e+07        22997        2170.995543 6273540.9644     12.565582   46.686489

================================================================================
STRONGEST COMPLETE YEAR
================================================================================
Year: 2013
Total Sales: $49,926,384.50
Total Orders: 22,997
Average Order Value: $2,171.00
Profit Margin: 12.57%

================================================================================
HIGHEST YEAR-OVER-YEAR GROWTH
================================================================================
Year: 2011
YoY Sales Growth: 4643.00%

In [ ]:
# Sales channel performance by year
channel_yearly = (
    fact_sales
    .assign(Year=fact_sales["OrderDate"].dt.year)
    .groupby(["Year", "SalesChannel"])
    .agg(
        TotalSales=("SalesAmount", "sum"),
        TotalOrders=("SalesOrderNumber", "nunique"),
        GrossProfit=("SalesAmount", lambda x: x.sum()),
        TotalCost=("TotalProductCost", "sum")
    )
    .reset_index()
)

# Calculate gross profit and AOV
channel_yearly["GrossProfit"] = (
    channel_yearly["TotalSales"]
    - channel_yearly["TotalCost"]
)

channel_yearly["ProfitMargin"] = (
    channel_yearly["GrossProfit"]
    / channel_yearly["TotalSales"]
    * 100
)

channel_yearly["AverageOrderValue"] = (
    channel_yearly["TotalSales"]
    / channel_yearly["TotalOrders"]
)

print("=" * 80)
print("SALES CHANNEL PERFORMANCE BY YEAR")
print("=" * 80)

print(
    channel_yearly.to_string(index=False)
)

print("\n" + "=" * 80)
print("OVERALL SALES CHANNEL PERFORMANCE")
print("=" * 80)

channel_overall = (
    fact_sales
    .groupby("SalesChannel")
    .agg(
        TotalSales=("SalesAmount", "sum"),
        TotalOrders=("SalesOrderNumber", "nunique"),
        TotalCost=("TotalProductCost", "sum")
    )
    .reset_index()
)

channel_overall["GrossProfit"] = (
    channel_overall["TotalSales"]
    - channel_overall["TotalCost"]
)

channel_overall["ProfitMargin"] = (
    channel_overall["GrossProfit"]
    / channel_overall["TotalSales"]
    * 100
)

channel_overall["AverageOrderValue"] = (
    channel_overall["TotalSales"]
    / channel_overall["TotalOrders"]
)

channel_overall["SalesShare"] = (
    channel_overall["TotalSales"]
    / total_sales
    * 100
)

print(
    channel_overall.to_string(index=False)
)

================================================================================
SALES CHANNEL PERFORMANCE BY YEAR
================================================================================
 Year SalesChannel   TotalSales  TotalOrders  GrossProfit    TotalCost  ProfitMargin  AverageOrderValue
 2010     Internet 4.342104e+04           14   17848.9724 2.557206e+04     41.106740        3101.502600
 2010     Reseller 4.893286e+05           38   17033.4360 4.722951e+05      3.480981       12877.067861
 2011     Internet 7.075526e+06         2216 2844063.7381 4.231462e+06     40.195793        3192.926863
 2011     Reseller 1.819280e+07          773   29420.1375 1.816338e+07      0.161713       23535.320458
 2012     Internet 5.842485e+06         3269 2428007.0259 3.414478e+06     41.557778        1787.239277
 2012     Reseller 2.819363e+07         1277  915899.0364 2.727773e+07      3.248603       22078.019994
 2013     Internet 1.635155e+07        21289 6765410.9710 9.586139e+06     41.374737         768.075078
 2013     Reseller 3.357483e+07         1708 -491870.0066 3.406670e+07     -1.464996       19657.397048
 2014     Internet 4.569472e+04          871   25552.9376 2.014178e+04     55.920985          52.462365

================================================================================
OVERALL SALES CHANNEL PERFORMANCE
================================================================================
SalesChannel   TotalSales  TotalOrders    TotalCost  GrossProfit  ProfitMargin  AverageOrderValue  SalesShare
    Internet 2.935868e+07        27659 1.727779e+07 1.208088e+07     41.149278        1061.451145   26.736063
    Reseller 8.045060e+07         3796 7.998011e+07 4.704826e+05      0.584809       21193.518699   73.263937

In [ ]:
# Final warehouse table collection
warehouse_tables = {
    "dim_customer": dim_customer_clean,
    "dim_employee": dim_employee_clean,
    "dim_geography": dim_geography_clean,
    "dim_product": dim_product_clean,
    "dim_reseller": dim_reseller_clean,
    "dim_sales_territory": dim_sales_territory_clean,
    "dim_date": dim_date,
    "fact_sales": fact_sales
}

print("=" * 80)
print("FINAL DATA WAREHOUSE TABLES")
print("=" * 80)

for table_name, df in warehouse_tables.items():
    print(
        f"{table_name:<25} "
        f"Rows: {len(df):>7,} | "
        f"Columns: {len(df.columns):>2}"
    )

print("\n" + "=" * 80)
print("WAREHOUSE PREPARATION STATUS")
print("=" * 80)

print("✓ Dimension tables prepared")
print("✓ Date dimension prepared")
print("✓ Customer age and age groups prepared")
print("✓ Internet and reseller sales combined")
print("✓ Sales channel identified")
print("✓ Data quality validation completed")
print("✓ Business analysis completed")
print("✓ Ready for MySQL warehouse loading")

================================================================================
FINAL DATA WAREHOUSE TABLES
================================================================================
dim_customer              Rows:  18,484 | Columns: 15
dim_employee              Rows:      21 | Columns:  9
dim_geography             Rows:     655 | Columns:  6
dim_product               Rows:     397 | Columns:  7
dim_reseller              Rows:     701 | Columns:  4
dim_sales_territory       Rows:      11 | Columns:  4
dim_date                  Rows:   1,127 | Columns:  9
fact_sales                Rows: 121,253 | Columns: 16

================================================================================
WAREHOUSE PREPARATION STATUS
================================================================================
✓ Dimension tables prepared
✓ Date dimension prepared
✓ Customer age and age groups prepared
✓ Internet and reseller sales combined
✓ Sales channel identified
✓ Data quality validation completed
✓ Business analysis completed
✓ Ready for MySQL warehouse loading

In [ ]:
# Export final warehouse tables for MySQL loading

export_path = "/content/adventure_works_dw"

os.makedirs(export_path, exist_ok=True)

for table_name, df in warehouse_tables.items():
    file_path = f"{export_path}/{table_name}.csv"
    df.to_csv(file_path, index=False)
    print(f"Exported: {table_name}.csv | Rows: {len(df):,}")

print("\n" + "=" * 80)
print("CSV EXPORT COMPLETED")
print("=" * 80)

print(f"Folder: {export_path}")
print(f"Total files: {len(warehouse_tables)}")

Exported: dim_customer.csv | Rows: 18,484
Exported: dim_employee.csv | Rows: 21
Exported: dim_geography.csv | Rows: 655
Exported: dim_product.csv | Rows: 397
Exported: dim_reseller.csv | Rows: 701
Exported: dim_sales_territory.csv | Rows: 11
Exported: dim_date.csv | Rows: 1,127
Exported: fact_sales.csv | Rows: 121,253

================================================================================
CSV EXPORT COMPLETED
================================================================================
Folder: /content/adventure_works_dw
Total files: 8

In [ ]:
# Verify exported CSV files

print("=" * 80)
print("EXPORTED CSV VALIDATION")
print("=" * 80)

for table_name, original_df in warehouse_tables.items():
    file_path = f"{export_path}/{table_name}.csv"

    exported_df = pd.read_csv(file_path)

    print(
        f"{table_name:<25} "
        f"Expected: {len(original_df):>7,} | "
        f"CSV: {len(exported_df):>7,} | "
        f"Status: {'MATCH' if len(original_df) == len(exported_df) else 'CHECK'}"
    )

print("\n" + "=" * 80)
print("FINAL CSV VALIDATION COMPLETED")
print("=" * 80)

================================================================================
EXPORTED CSV VALIDATION
================================================================================
dim_customer              Expected:  18,484 | CSV:  18,484 | Status: MATCH
dim_employee              Expected:      21 | CSV:      21 | Status: MATCH
dim_geography             Expected:     655 | CSV:     655 | Status: MATCH
dim_product               Expected:     397 | CSV:     397 | Status: MATCH
dim_reseller              Expected:     701 | CSV:     701 | Status: MATCH
dim_sales_territory       Expected:      11 | CSV:      11 | Status: MATCH
dim_date                  Expected:   1,127 | CSV:   1,127 | Status: MATCH
fact_sales                Expected: 121,253 | CSV: 121,253 | Status: MATCH

================================================================================
FINAL CSV VALIDATION COMPLETED
================================================================================

/tmp/ipykernel_3354/2560097453.py:10: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  exported_df = pd.read_csv(file_path)

In [ ]:
# Remove the column that contains no analytical information
fact_sales_clean = fact_sales.drop(columns=["CarrierTrackingNumber"]).copy()

print("Updated Fact Sales Shape:", fact_sales_clean.shape)
print("\nColumns:")
print(fact_sales_clean.columns.tolist())

Updated Fact Sales Shape: (121253, 15)

Columns:
['ProductKey', 'CustomerKey', 'ResellerKey', 'EmployeeKey', 'SalesTerritoryKey', 'SalesOrderNumber', 'SalesOrderLineNumber', 'DiscountAmount', 'TotalProductCost', 'SalesAmount', 'Freight', 'OrderDate', 'DueDate', 'ShipDate', 'SalesChannel']

In [ ]:
# Export corrected Fact Sales table
output_path = "/content/adventure_works_dw/fact_sales.csv"

fact_sales_clean.to_csv(output_path, index=False)

print(f"Corrected file exported successfully: {output_path}")
print(f"Rows: {len(fact_sales_clean):,}")
print(f"Columns: {len(fact_sales_clean.columns)}")

Corrected file exported successfully: /content/adventure_works_dw/fact_sales.csv
Rows: 121,253
Columns: 15